"""Render recaps + story permalinks to static HTML + sitemap for SEO/previews.

The /daily and /weekly pages are client-rendered JS shells, so crawlers and
link unfurlers see "Loading…" instead of content. This script turns the recap
JSON the pipeline already commits (``data/daily/<date>.json``,
``data/weekly/<week>.json``) and the durable story store
(``data/stories/<YYYY-MM>.json``, see ``pipeline/story_store.py``) into fully
static, indexable pages:

- ``web/daily/<date>.html``    served at ``/daily/<date>``
- ``web/weekly/<week>.html``   served at ``/weekly/<week>``
- ``web/story/<sid>.html``     served at ``/story/<sid>``
- ``web/storyline/<slug>.html`` served at ``/storyline/<slug>``
- ``web/sitemap.xml``          served at ``/sitemap.xml``
- ``web/robots.txt``           served at ``/robots.txt``

Story pages are the durable landing target for shares (``api/share.js``
redirects there) and give every story that made the published feed an
indexable page with internal links (related stories, recap pages), so search
and share traffic land on llm-digest.com instead of expiring with feed
retention.

Storyline pages are the SEO surface for the "what happened next" threads: one
static page per timeline file in ``data/storylines/`` (those are never pruned,
so shared links keep working), with the agent-written editorial overlay and the
day-by-day item list rendered server-side. A minimal Follow button mirrors the
localStorage contract of the dynamic ``web/storyline.html`` shell.

Each page carries a real <title>, meta description, canonical URL, Open
Graph/Twitter cards (defaulting to the branded ``/og-default.png`` card),
NewsArticle + BreadcrumbList JSON-LD, a favicon, and RSS autodiscovery — and
mirrors the markup and styles of the dynamic pages so the reader experience is
identical.

Off-topic story pages (no AI/platform signal, not a release/paper/research item
and not part of a storyline; see ``is_on_topic``) are still rendered so shared
links resolve, but get ``robots=noindex,follow`` and are kept out of the
sitemap to protect topical authority.

Stale pages whose recap/story/storyline JSON no longer exists are pruned.

Stdlib only, like the rest of the recap tooling. Run after rebuilding the
recap indexes (build_daily_index.py / build_weekly_index.py do this
automatically):

    python pipeline/render_static_pages.py [--base-url https://example.com]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import date, datetime, timezone
from html import escape
from pathlib import Path
from urllib.parse import quote, urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))
from story_store import load_store, parse_dt, story_sid  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DAILY_DIR = ROOT / "data" / "daily"
WEEKLY_DIR = ROOT / "data" / "weekly"
STORYLINES_DIR = ROOT / "data" / "storylines"
WEB_DIR = ROOT / "web"

DEFAULT_BASE_URL = os.environ.get("SITE_BASE_URL", "https://www.llm-digest.com")
SITE_NAME = "LLM Digest"
# Branded social card + publisher logo, generated by scripts/make_og_assets.py.
DEFAULT_OG_IMAGE = "/og-default.png"
LOGO_PATH = "/logo.png"

DATE_FILE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}\.json$")
WEEK_FILE_RE = re.compile(r"^\d{4}-W\d{2}\.json$")
DATE_HTML_RE = re.compile(r"^\d{4}-\d{2}-\d{2}\.html$")
WEEK_HTML_RE = re.compile(r"^\d{4}-W\d{2}\.html$")
SID_HTML_RE = re.compile(r"^[0-9a-f]{16}\.html$")
SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,80}$")
SLUG_HTML_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,80}\.html$")

RELATED_STORIES_MAX = 4

# Topical-authority gate: the feed lets through occasional off-topic posts from
# otherwise-relevant sources (e.g. a frontier lab's consumer/PR announcement).
# Giving those a thin, indexable permalink dilutes our "AI platform engineer"
# topical authority, so they get robots=noindex,follow (link equity still flows
# to related stories) and are kept out of the sitemap. A story is on-topic when
# any AI/platform term appears in its title/summary, OR it is a release/paper/
# research item, OR it belongs to a storyline — conservative by design so we
# only suppress obvious noise. Keep AI_TERMS roughly in sync with
# config/profile.yaml `platform_keywords`.
AI_TERMS = frozenset(
    {
        "ai", "a.i.", "llm", "llms", "gpt", "claude", "gemini", "llama", "mistral",
        "model", "models", "agent", "agents", "agentic", "ml", "neural", "transformer",
        "transformers", "diffusion", "embedding", "embeddings", "rag", "fine-tune",
        "fine-tuning", "finetuning", "inference", "training", "pretraining", "prompt",
        "prompting", "token", "tokens", "context window", "mcp", "openai", "anthropic",
        "deepmind", "hugging face", "huggingface", "vllm", "tensor", "gpu", "cuda",
        # config/profile.yaml platform_keywords
        "serving", "latency", "throughput", "quantization", "eval", "evals",
        "observability", "orchestration", "kubernetes", "triton", "tgi", "benchmark",
        "context", "knowledge", "memory", "retrieval", "interoperab", "tool use",
    }
)
ON_TOPIC_TYPES = frozenset({"release", "paper", "research"})

# Same look as web/daily.html / web/weekly.html so static and dynamic pages
# are indistinguishable to readers. Keep in sync when restyling those shells.
PAGE_CSS = """\
    html { font-size: 16px; -webkit-text-size-adjust: 100%; text-size-adjust: 100%; }
    :root, html[data-theme="light"] {
      --bg: #ffffff; --fg: #1a1a1a; --card: #ffffff; --border: #e5e5e5; --accent: #2563eb; --muted: #6b7280;
    }
    html[data-theme="dark"] {
      --bg: #15171c; --fg: #e8e8ea; --card: #1e2128; --border: #34373f; --accent: #5b8def; --muted: #9aa0aa;
    }
    body { margin: 0; line-height: 1.5; overflow-x: hidden; background: var(--bg); color: var(--fg); }
    *, *::before, *::after { box-sizing: border-box; }
    button, input, select, textarea { color: inherit; background: var(--card); border-color: var(--border); }
    a { color: var(--accent); }
    main { width: 100%; max-width: 860px; margin: 1rem auto; padding: 0 0.9rem 3rem; overflow-x: clip; }
    header { margin-bottom: 1rem; }
    .topbar { display: flex; align-items: center; justify-content: space-between; gap: 0.75rem; }
    .topbar h1 { margin: 0; font-size: 1.5rem; line-height: 1.2; overflow-wrap: anywhere; }
    menu { display: flex; flex-wrap: wrap; gap: 0.75rem; padding: 0; margin: 0.75rem 0 0; align-items: center; }
    .muted { color: var(--muted); }
    .recap-title { font-size: 1.7rem; margin: 1.2rem 0 0.2rem; line-height: 1.25; }
    .recap-range { color: var(--muted); margin: 0 0 1rem; font-size: 0.98rem; }
    .intro { font-size: 1.05rem; background: var(--card); border: 1px solid var(--border);
      border-radius: 12px; padding: 1rem 1.1rem; margin: 0 0 1.5rem; }
    .intro p { margin: 0 0 0.75rem; }
    .intro p:last-child { margin-bottom: 0; }
    .tldr { margin: 0 0 1rem; padding: 0 0 0.9rem; border-bottom: 1px solid var(--border); }
    .tldr-label { text-transform: uppercase; letter-spacing: 0.05em; font-size: 0.72rem;
      font-weight: 600; color: var(--muted); margin: 0 0 0.55rem; }
    .tldr ul { margin: 0; padding-left: 1.15rem; display: flex; flex-direction: column; gap: 0.4rem; }
    .tldr li { font-size: 0.95rem; line-height: 1.45; }
    .toc { display: flex; flex-wrap: wrap; gap: 0.4rem; margin: 0 0 1.5rem; }
    .toc a { font-size: 0.9rem; padding: 0.3rem 0.7rem; border: 1px solid var(--border);
      border-radius: 999px; text-decoration: none; }
    .toc a:hover { border-color: var(--accent); }
    .cat { margin: 0 0 2rem; scroll-margin-top: 1rem; }
    .cat h2 { font-size: 1.25rem; margin: 0 0 0.25rem; display: flex; align-items: baseline; gap: 0.5rem; }
    .cat h2 .count { font-size: 0.85rem; color: var(--muted); font-weight: 400; }
    .cat-summary { color: var(--fg); opacity: 0.9; margin: 0 0 0.9rem; }
    .articles { display: flex; flex-direction: column; gap: 0.7rem; }
    article { border: 1px solid var(--border); border-radius: 10px; padding: 0.8rem 0.9rem; background: var(--card); }
    article h3 { margin: 0 0 0.3rem; font-size: 1.02rem; line-height: 1.35; }
    article h3 a { text-decoration: none; }
    article h3 a:hover { text-decoration: underline; }
    .art-meta { display: flex; flex-wrap: wrap; gap: 0.4rem; align-items: center; margin-bottom: 0.3rem; }
    .badge { font-size: 0.72rem; padding: 0.1rem 0.5rem; font-weight: 500;
      border: 1px solid color-mix(in srgb, var(--accent) 35%, transparent);
      border-radius: 999px; color: var(--accent);
      background: color-mix(in srgb, var(--accent) 14%, var(--card)); white-space: nowrap; }
    .art-summary { margin: 0.1rem 0 0; font-size: 0.95rem; }
    .archive { margin-left: auto; }
    footer { margin-top: 2rem; color: var(--muted); font-size: 0.85rem; }
    .story-title a { text-decoration: none; color: inherit; }
    .story-title a:hover { text-decoration: underline; }
    .story-img { float: right; width: 96px; height: 96px; object-fit: cover;
      border-radius: 10px; border: 1px solid var(--border); margin: 0 0 0.6rem 0.8rem; }
    .story-summary { font-size: 1.02rem; margin: 0 0 1.2rem; }
    .chips { display: flex; flex-wrap: wrap; gap: 0.4rem; margin: 0 0 1.2rem; }
    .story-actions { display: flex; flex-wrap: wrap; gap: 0.6rem; margin: 0 0 1.6rem; }
    .story-actions a { font-size: 0.92rem; padding: 0.45rem 0.85rem; border: 1px solid var(--border);
      border-radius: 10px; text-decoration: none; background: var(--card); }
    .story-actions a.primary { border-color: var(--accent);
      background: color-mix(in srgb, var(--accent) 12%, var(--card)); }
    .story-actions a:hover { border-color: var(--accent); }
    .covered { margin: 0 0 1.6rem; }
    .covered ul { margin: 0.4rem 0 0; padding-left: 1.15rem; }
    .covered li { margin: 0.25rem 0; font-size: 0.95rem; }
"""

THEME_BOOT_JS = """\
    (function () {
      var t = localStorage.getItem('theme') || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
      document.documentElement.setAttribute('data-theme', t);
    })();
"""

PAGE_JS = """\
    (function () {
      function applyTheme(theme) {
        document.documentElement.setAttribute('data-theme', theme);
        localStorage.setItem('theme', theme);
        var btn = document.getElementById('themeToggle');
        if (btn) btn.textContent = theme === 'dark' ? '☀️ Light' : '🌙 Dark';
      }
      var btn = document.getElementById('themeToggle');
      if (btn) {
        applyTheme(document.documentElement.getAttribute('data-theme') || 'light');
        btn.addEventListener('click', function () {
          var now = document.documentElement.getAttribute('data-theme') || 'light';
          applyTheme(now === 'dark' ? 'light' : 'dark');
        });
      }
      var sel = document.getElementById('archive');
      if (sel) sel.addEventListener('change', function () { window.location.href = sel.value; });
    })();
"""

# Follow button for static storyline pages. Mirrors the localStorage contract
# in web/storyline.html (FOLLOWS_KEY ai_feed_storyline_follows_v1) so a follow
# made on a static page is recognized by the dynamic /storylines list and vice
# versa. PostHog capture is intentionally omitted (optional/secret-gated).
STORYLINE_FOLLOW_JS = """\
    (function () {
      var KEY = 'ai_feed_storyline_follows_v1';
      var btn = document.getElementById('followBtn');
      if (!btn) return;
      function load() { try { return JSON.parse(localStorage.getItem(KEY) || '{}'); } catch (e) { return {}; } }
      function save(f) { try { localStorage.setItem(KEY, JSON.stringify(f)); } catch (e) {} }
      var slug = btn.dataset.slug, lu = btn.dataset.lastUpdated || '';
      function paint() {
        var on = !!load()[slug];
        btn.setAttribute('aria-pressed', on ? 'true' : 'false');
        btn.textContent = on ? '\\u2713 Following' : '+ Follow this story';
      }
      paint();
      btn.addEventListener('click', function () {
        var f = load();
        if (f[slug]) { delete f[slug]; }
        else { f[slug] = { followed_at: new Date().toISOString(), seen_updated: lu }; }
        save(f);
        paint();
      });
    })();
"""


def load_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def squeeze(text: str) -> str:
    return " ".join(str(text or "").split())


def clip(text: str, limit: int) -> str:
    text = squeeze(text)
    if len(text) <= limit:
        return text
    cut = text[: limit - 1].rsplit(" ", 1)[0]
    return cut + "…"


def intro_paragraphs(intro) -> list[str]:
    if isinstance(intro, list):
        return [squeeze(p) for p in intro if squeeze(p)]
    return [squeeze(p) for p in re.split(r"\n{2,}", str(intro or "")) if squeeze(p)]


def recap_description(recap: dict) -> str:
    """Meta/OG description: first highlight(s) if present, else the intro."""
    highlights = [squeeze(h) for h in recap.get("highlights") or [] if squeeze(h)]
    if highlights:
        return clip(" ".join(highlights), 250)
    paras = intro_paragraphs(recap.get("intro"))
    return clip(paras[0] if paras else "", 250)


def iso_or_none(value) -> str | None:
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00")).isoformat()
    except Exception:
        return None


def fmt_long_date(day_id: str) -> str:
    """e.g. 'Wednesday, Jun 10, 2026' (matches the dynamic page header)."""
    try:
        d = date.fromisoformat(day_id)
    except Exception:
        return str(day_id)
    return f"{d.strftime('%A')}, {d.strftime('%b')} {d.day}, {d.year}"


def safe_http_url(value) -> str:
    s = str(value or "").strip()
    return s if s.startswith("http://") or s.startswith("https://") else "#"


def render_intro(recap: dict) -> str:
    paras = intro_paragraphs(recap.get("intro"))
    highlights = [squeeze(h) for h in recap.get("highlights") or [] if squeeze(h)]
    if not paras and not highlights:
        return ""
    tldr = ""
    if highlights:
        items = "".join(f"<li>{escape(h)}</li>" for h in highlights)
        tldr = (
            '<div class="tldr"><p class="tldr-label">In 30 seconds</p>'
            f"<ul>{items}</ul></div>"
        )
    body = "".join(f"<p>{escape(p)}</p>" for p in paras)
    return f'<div class="intro">{tldr}{body}</div>'


def render_categories(recap: dict, track: str, story_sids: set[str] | None = None) -> str:
    cats = [c for c in recap.get("categories") or [] if isinstance(c, dict)]
    toc = ""
    if len(cats) > 1:
        links = "".join(
            f'<a href="#{escape(str(c.get("slug") or c.get("name") or ""))}">'
            f'{escape(str(c.get("name") or ""))} ({len(c.get("articles") or [])})</a>'
            for c in cats
        )
        toc = f'<nav class="toc">{links}</nav>'

    sections = []
    for c in cats:
        arts = []
        for a in c.get("articles") or []:
            if not isinstance(a, dict):
                continue
            href = safe_http_url(a.get("url"))
            pub = iso_or_none(a.get("published"))
            pub_badge = ""
            if pub:
                d = datetime.fromisoformat(pub)
                pub_badge = f'<span class="badge">{escape(d.strftime("%b"))} {d.day}</span>'
            src_badge = (
                f'<span class="badge">{escape(str(a.get("source")))}</span>'
                if a.get("source")
                else ""
            )
            # Internal link to the story permalink page (hub -> spoke), kept
            # alongside the external title link so titles still go to sources.
            sid = story_sid(a.get("url")) if href != "#" else ""
            detail_link = (
                f'<a class="badge" href="/story/{sid}" data-track="story-link">Details</a>'
                if story_sids and sid in story_sids
                else ""
            )
            summary = (
                f'<p class="art-summary">{escape(squeeze(a.get("summary")))}</p>'
                if squeeze(a.get("summary"))
                else ""
            )
            arts.append(
                "<article>"
                f'<h3><a href="{escape(href)}" target="_blank" rel="noopener" data-track="{track}">'
                f'{escape(squeeze(a.get("title")) or "Untitled")}</a></h3>'
                f'<div class="art-meta">{src_badge}{pub_badge}{detail_link}</div>'
                f"{summary}</article>"
            )
        n = len(arts)
        cat_summary = (
            f'<p class="cat-summary">{escape(squeeze(c.get("summary")))}</p>'
            if squeeze(c.get("summary"))
            else ""
        )
        sections.append(
            f'<section class="cat" id="{escape(str(c.get("slug") or c.get("name") or ""))}">'
            f'<h2>{escape(str(c.get("name") or ""))} <span class="count">{n} item{"" if n == 1 else "s"}</span></h2>'
            f'{cat_summary}<div class="articles">{"".join(arts)}</div></section>'
        )
    return toc + "".join(sections)


def render_archive_select(options: list[tuple[str, str]], current: str, label: str) -> str:
    """Static archive picker; options are (href, text) pairs, newest first."""
    opts = "".join(
        f'<option value="{escape(href)}"{" selected" if href == current else ""}>{escape(text)}</option>'
        for href, text in options
    )
    return (
        f'<label class="archive muted">{escape(label)} '
        f'<select id="archive" aria-label="Choose {escape(label.lower())}">{opts}</select></label>'
    )


def publisher_node(base_url: str) -> dict:
    """schema.org Organization for the publisher, with a logo (rich-result req)."""
    return {
        "@type": "Organization",
        "name": SITE_NAME,
        "url": base_url + "/",
        "logo": {"@type": "ImageObject", "url": base_url + LOGO_PATH},
    }


def breadcrumb_node(base_url: str, trail: list[tuple[str, str]]) -> dict:
    """BreadcrumbList from (name, path) pairs, e.g. [('Home','/'),('Daily','/daily')]."""
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": i + 1,
                "name": name,
                "item": base_url + path,
            }
            for i, (name, path) in enumerate(trail)
        ],
    }


def article_node(
    *,
    type_: str,
    title: str,
    description: str,
    canonical: str,
    published: str | None,
    base_url: str,
    image: str = "",
    source_url: str = "",
) -> dict:
    """schema.org Article/NewsArticle node for a recap, story, or storyline."""
    node: dict = {
        "@type": type_,
        "headline": title,
        "description": description,
        "datePublished": published,
        "mainEntityOfPage": canonical,
        "publisher": publisher_node(base_url),
    }
    if image.startswith(("http://", "https://")):
        node["image"] = image
    if source_url.startswith(("http://", "https://")):
        node["isBasedOn"] = source_url  # the original we summarize/link to
    return node


def json_ld_script(nodes: list[dict]) -> str:
    """One <script> carrying a @graph of schema.org nodes (or a single node)."""
    nodes = [n for n in nodes if n]
    if not nodes:
        return ""
    if len(nodes) == 1:
        payload = {"@context": "https://schema.org", **nodes[0]}
    else:
        payload = {"@context": "https://schema.org", "@graph": nodes}
    # Page text must never be able to close the surrounding </script>.
    encoded = json.dumps(payload, ensure_ascii=False).replace("</", "<\\/")
    return f'\n  <script type="application/ld+json">{encoded}</script>'


def render_head(
    *,
    title: str,
    description: str,
    canonical: str,
    published: str | None,
    image: str = "",
    og_type: str = "article",
    robots: str = "",
    json_ld: list[dict] | None = None,
) -> str:
    og_published = (
        f'\n  <meta property="article:published_time" content="{escape(published)}" />'
        if published and og_type == "article"
        else ""
    )
    # Fall back to the branded default card so every static page shares with an
    # image. Origin is derived from the canonical URL (which already carries the
    # configured base URL) so a custom --base-url stays consistent.
    if not image.startswith(("http://", "https://")):
        split = urlsplit(canonical)
        if split.scheme and split.netloc:
            image = f"{split.scheme}://{split.netloc}{DEFAULT_OG_IMAGE}"
    has_image = image.startswith(("http://", "https://"))
    og_image = (
        f'\n  <meta property="og:image" content="{escape(image)}" />'
        f'\n  <meta name="twitter:image" content="{escape(image)}" />'
        if has_image
        else ""
    )
    robots_meta = (
        f'\n  <meta name="robots" content="{escape(robots)}" />' if robots else ""
    )
    twitter_card = "summary_large_image" if has_image else "summary"
    ld = json_ld_script(json_ld or [])
    return f"""\
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />{robots_meta}
  <title>{escape(title)} | {escape(SITE_NAME)}</title>
  <meta name="description" content="{escape(description)}" />
  <link rel="canonical" href="{escape(canonical)}" />
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <link rel="icon" href="/favicon-32.png" sizes="32x32" type="image/png" />
  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
  <link rel="manifest" href="/site.webmanifest" />
  <meta property="og:type" content="{escape(og_type)}" />
  <meta property="og:site_name" content="{escape(SITE_NAME)}" />
  <meta property="og:title" content="{escape(title)}" />
  <meta property="og:description" content="{escape(description)}" />
  <meta property="og:url" content="{escape(canonical)}" />{og_published}{og_image}
  <meta name="twitter:card" content="{twitter_card}" />
  <meta name="twitter:title" content="{escape(title)}" />
  <meta name="twitter:description" content="{escape(description)}" />{ld}
  <link rel="alternate" type="application/rss+xml" title="{escape(SITE_NAME)} feed" href="/rss.xml" />
  <link rel="stylesheet" href="https://oat.ink/oat.min.css" />
  <script defer src="/_vercel/speed-insights/script.js"></script>
  <script>
{THEME_BOOT_JS}  </script>
  <style>
{PAGE_CSS}  </style>"""


def render_page(
    *,
    title: str,
    description: str,
    canonical: str,
    published: str | None,
    h1: str,
    meta_line: str,
    nav_links: list[tuple[str, str]],
    json_href: str,
    archive: str,
    recap_title: str,
    recap_range: str,
    intro_html: str,
    body_html: str,
    image: str = "",
    title_html: str = "",
    og_type: str = "article",
    robots: str = "",
    json_ld: list[dict] | None = None,
    extra_js: str = "",
) -> str:
    nav = "".join(f'\n        <a href="{escape(h)}" role="button">{escape(t)}</a>' for h, t in nav_links)
    json_link = f'\n        <a href="{escape(json_href)}" role="button">JSON</a>' if json_href else ""
    heading = title_html or f'<h2 class="recap-title">{escape(recap_title)}</h2>'
    range_line = f'<p class="recap-range">{escape(recap_range)}</p>' if recap_range else ""
    return f"""<!doctype html>
<html lang="en">
<head>
{render_head(title=title, description=description, canonical=canonical, published=published, image=image, og_type=og_type, robots=robots, json_ld=json_ld)}
</head>
<body>
  <main>
    <header>
      <div class="topbar">
        <h1>{h1}</h1>
        <button id="themeToggle" type="button" aria-label="Toggle theme">🌙 Dark</button>
      </div>
      <p id="meta" class="muted">{escape(meta_line)}</p>
      <menu>{nav}{json_link}
        {archive}
      </menu>
    </header>

    <section id="recap">
      {heading}
      {range_line}
      {intro_html}
      {body_html}
    </section>

    <footer>
      Built from the AI SOTA feed. Each item links to its original source. ·
      <a href="/rss.xml">RSS</a>
    </footer>
  </main>
  <script>
{PAGE_JS}{extra_js}  </script>
</body>
</html>
"""


def load_recaps(directory: Path, file_re: re.Pattern, id_field: str) -> list[dict]:
    recaps = []
    if not directory.is_dir():
        return recaps
    for path in sorted(directory.glob("*.json")):
        if not file_re.match(path.name):
            continue
        data = load_json(path)
        if isinstance(data, dict) and data.get(id_field) and data.get("categories"):
            recaps.append(data)
    recaps.sort(key=lambda r: str(r.get(id_field)), reverse=True)
    return recaps


def meta_line_for(recap: dict) -> str:
    cats = recap.get("categories") or []
    total = recap.get("article_count") or sum(len(c.get("articles") or []) for c in cats)
    return f"{total} articles · {len(cats)} categories"


def render_daily_pages(base_url: str, story_sids: set[str] | None = None) -> list[str]:
    recaps = load_recaps(DAILY_DIR, DATE_FILE_RE, "date")
    out_dir = WEB_DIR / "daily"
    archive_options = [
        (f"/daily/{r['date']}", f"{r['date']} · {squeeze(r.get('title'))}") for r in recaps
    ]
    ids = []
    for recap in recaps:
        day = str(recap["date"])
        canonical = f"{base_url}/daily/{day}"
        title = squeeze(recap.get("title")) or f"AI Daily Recap — {day}"
        description = recap_description(recap)
        published = iso_or_none(recap.get("generated_at"))
        html = render_page(
            title=title,
            description=description,
            canonical=canonical,
            published=published,
            h1="📰 AI Daily Recap",
            meta_line=meta_line_for(recap),
            nav_links=[("/", "← Live feed"), ("/weekly", "🗓️ Weekly recap"), ("/voices", "🗣️ Voices"), ("/rss.xml", "🔔 RSS")],
            json_href=f"/api/daily?date={day}",
            archive=render_archive_select(archive_options, f"/daily/{day}", "Day"),
            recap_title=squeeze(recap.get("title")) or day,
            recap_range=fmt_long_date(day),
            intro_html=render_intro(recap),
            body_html=render_categories(recap, "daily-link", story_sids),
            json_ld=[
                article_node(
                    type_="NewsArticle",
                    title=title,
                    description=description,
                    canonical=canonical,
                    published=published,
                    base_url=base_url,
                ),
                breadcrumb_node(
                    base_url,
                    [("Home", "/"), ("Daily recaps", "/daily"), (day, f"/daily/{day}")],
                ),
            ],
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{day}.html").write_text(html, encoding="utf-8")
        ids.append(day)
    prune_orphans(out_dir, DATE_HTML_RE, {f"{i}.html" for i in ids})
    return ids


def render_weekly_pages(base_url: str, story_sids: set[str] | None = None) -> list[str]:
    recaps = load_recaps(WEEKLY_DIR, WEEK_FILE_RE, "week")
    out_dir = WEB_DIR / "weekly"
    archive_options = [
        (f"/weekly/{r['week']}", f"{r['week']} · {squeeze(r.get('title'))}") for r in recaps
    ]
    ids = []
    for recap in recaps:
        week = str(recap["week"])
        canonical = f"{base_url}/weekly/{week}"
        recap_range = " – ".join(
            s for s in (str(recap.get("start") or ""), str(recap.get("end") or "")) if s
        )
        title = squeeze(recap.get("title")) or f"AI Weekly Recap — {week}"
        description = recap_description(recap)
        published = iso_or_none(recap.get("generated_at"))
        html = render_page(
            title=title,
            description=description,
            canonical=canonical,
            published=published,
            h1="🗓️ AI Weekly Recap",
            meta_line=meta_line_for(recap),
            nav_links=[("/", "← Live feed"), ("/daily", "📰 Daily recap"), ("/voices", "🗣️ Voices"), ("/rss.xml", "🔔 RSS")],
            json_href=f"/api/weekly?week={week}",
            archive=render_archive_select(archive_options, f"/weekly/{week}", "Week"),
            recap_title=squeeze(recap.get("title")) or week,
            recap_range=f"{recap_range} · {week}" if recap_range else week,
            intro_html=render_intro(recap),
            body_html=render_categories(recap, "weekly-link", story_sids),
            json_ld=[
                article_node(
                    type_="NewsArticle",
                    title=title,
                    description=description,
                    canonical=canonical,
                    published=published,
                    base_url=base_url,
                ),
                breadcrumb_node(
                    base_url,
                    [("Home", "/"), ("Weekly recaps", "/weekly"), (week, f"/weekly/{week}")],
                ),
            ],
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{week}.html").write_text(html, encoding="utf-8")
        ids.append(week)
    prune_orphans(out_dir, WEEK_HTML_RE, {f"{i}.html" for i in ids})
    return ids


def story_dt(rec: dict) -> datetime:
    dt = parse_dt(rec.get("published")) or parse_dt(rec.get("first_seen"))
    return dt or datetime.fromtimestamp(0, tz=timezone.utc)


def fmt_story_date(dt: datetime) -> str:
    return f"{dt.strftime('%b')} {dt.day}, {dt.year}"


def source_domain(url: str) -> str:
    try:
        host = urlsplit(url).hostname or ""
    except ValueError:
        host = ""
    return host.removeprefix("www.") or "the source"


def is_on_topic(rec: dict, storyline_sids: set[str]) -> bool:
    """Whether a story deserves an indexable permalink (see AI_TERMS docstring).

    Conservative: index unless the page shows no AI/platform signal at all and
    isn't a release/paper/research item or part of a storyline.
    """
    if str(rec.get("type") or "").lower() in ON_TOPIC_TYPES:
        return True
    if str(rec.get("sid") or "") in storyline_sids:
        return True
    if rec.get("matched_topics"):
        return True
    haystack = " ".join(
        str(rec.get(f) or "")
        for f in ("title", "summary", "summary_1line", "why_it_matters")
    ).lower()
    return any(term in haystack for term in AI_TERMS)


def related_stories(rec: dict, stories: dict[str, dict]) -> list[dict]:
    """Related = shared topic or same source, published at/before this story.

    Only looking backward keeps rendered pages stable as new stories arrive
    (no churn re-committing every page each run).
    """
    topics = set(rec.get("matched_topics") or [])
    cutoff = story_dt(rec)
    scored = []
    for other in stories.values():
        if other.get("sid") == rec.get("sid") or story_dt(other) > cutoff:
            continue
        shared = len(topics & set(other.get("matched_topics") or []))
        same_source = other.get("source") == rec.get("source")
        if shared or same_source:
            scored.append((2 * shared + int(same_source), story_dt(other), other))
    scored.sort(key=lambda t: (t[0], t[1]), reverse=True)
    return [other for _, _, other in scored[:RELATED_STORIES_MAX]]


def render_story_body(rec: dict, stories: dict[str, dict]) -> str:
    parts = []
    why = squeeze(rec.get("why_it_matters"))
    if why:
        parts.append(
            '<div class="intro"><p class="tldr-label">Why it matters</p>'
            f"<p>{escape(why)}</p></div>"
        )

    img = str(rec.get("image_url") or "")
    img_html = (
        f'<img class="story-img" src="{escape(img)}" alt="" loading="lazy" '
        'onerror="this.remove()" />'
        if img.startswith(("http://", "https://"))
        else ""
    )
    highlights = [squeeze(h) for h in rec.get("release_highlights") or [] if squeeze(h)]
    # Release summaries are built from the same changelog bullets as the
    # highlights, so showing both would duplicate the page.
    summary = "" if highlights else squeeze(rec.get("summary") or rec.get("summary_1line"))
    if summary:
        parts.append(f'<p class="story-summary">{img_html}{escape(summary)}</p>')
    elif img_html:
        parts.append(f'<p class="story-summary">{img_html}</p>')

    if highlights:
        items = "".join(f"<li>{escape(h)}</li>" for h in highlights)
        parts.append(
            '<div class="tldr"><p class="tldr-label">Release highlights</p>'
            f"<ul>{items}</ul></div>"
        )

    topics = [squeeze(t) for t in rec.get("matched_topics") or [] if squeeze(t)]
    if topics:
        chips = "".join(f'<span class="badge">{escape(t)}</span>' for t in topics)
        parts.append(f'<div class="chips">{chips}</div>')

    url = str(rec.get("url") or "")
    feed_link = f"/?item={quote(url, safe='')}&utm_source=story"
    actions = [
        f'<a class="primary" href="{escape(url)}" target="_blank" rel="noopener" '
        f'data-track="story-source">Read the original at {escape(source_domain(url))} →</a>',
        f'<a href="{escape(feed_link)}">Open in live feed</a>',
    ]
    day = story_dt(rec).date().isoformat()
    if (DAILY_DIR / f"{day}.json").is_file():
        actions.append(f'<a href="/daily/{day}">Daily recap for {escape(day)}</a>')
    parts.append(f'<div class="story-actions">{"".join(actions)}</div>')

    covered = [c for c in rec.get("also_covered") or [] if isinstance(c, dict)]
    if covered:
        rows = []
        for c in covered:
            href = safe_http_url(c.get("url"))
            label = squeeze(c.get("title")) or squeeze(c.get("source")) or href
            src = squeeze(c.get("source"))
            suffix = f' <span class="muted">({escape(src)})</span>' if src else ""
            rows.append(
                f'<li><a href="{escape(href)}" target="_blank" rel="noopener">'
                f"{escape(label)}</a>{suffix}</li>"
            )
        parts.append(
            '<div class="covered"><p class="tldr-label">Also covered by</p>'
            f'<ul>{"".join(rows)}</ul></div>'
        )

    related = related_stories(rec, stories)
    if related:
        cards = []
        for other in related:
            meta = []
            if other.get("source"):
                meta.append(f'<span class="badge">{escape(str(other["source"]))}</span>')
            meta.append(f'<span class="badge">{escape(fmt_story_date(story_dt(other)))}</span>')
            cards.append(
                "<article>"
                f'<h3><a href="/story/{escape(str(other.get("sid")))}" data-track="story-related">'
                f'{escape(squeeze(other.get("title")) or "Untitled")}</a></h3>'
                f'<div class="art-meta">{"".join(meta)}</div></article>'
            )
        parts.append(
            '<section class="cat"><h2>Related stories '
            f'<span class="count">{len(cards)} item{"" if len(cards) == 1 else "s"}</span></h2>'
            f'<div class="articles">{"".join(cards)}</div></section>'
        )
    return "".join(parts)


def render_story_pages(
    base_url: str, stories: dict[str, dict], storyline_sids: set[str] | None = None
) -> tuple[list[tuple[str, str | None]], int]:
    """Render web/story/<sid>.html for every stored story.

    Every story still gets a page (so shared links keep resolving), but
    off-topic stories are rendered with robots=noindex,follow and excluded from
    the returned sitemap list. Returns (sitemap_entries, noindexed_count) where
    sitemap_entries are (sid, lastmod) pairs newest first.
    """
    out_dir = WEB_DIR / "story"
    storyline_sids = storyline_sids or set()
    sitemap_entries: list[tuple[str, str | None]] = []
    written: set[str] = set()
    noindexed = 0
    ordered = sorted(stories.values(), key=story_dt, reverse=True)
    for rec in ordered:
        sid = str(rec.get("sid") or "")
        url = str(rec.get("url") or "")
        title = squeeze(rec.get("title"))
        if not SID_HTML_RE.match(f"{sid}.html") or not title or not url:
            continue
        canonical = f"{base_url}/story/{sid}"
        published_dt = parse_dt(rec.get("published"))
        published = published_dt.isoformat() if published_dt else None
        description = clip(
            squeeze(rec.get("why_it_matters"))
            or squeeze(rec.get("summary_1line"))
            or squeeze(rec.get("summary")),
            250,
        )
        source = squeeze(rec.get("source"))
        kind = squeeze(rec.get("type"))
        meta_bits = [b for b in (source, fmt_story_date(story_dt(rec)), kind) if b]
        image = str(rec.get("image_url") or "")
        on_topic = is_on_topic(rec, storyline_sids)
        html = render_page(
            title=title,
            description=description,
            canonical=canonical,
            published=published,
            h1="📰 Story",
            meta_line=" · ".join(meta_bits),
            nav_links=[("/", "← Live feed"), ("/daily", "📰 Daily recap"), ("/weekly", "🗓️ Weekly recap"), ("/rss.xml", "🔔 RSS")],
            json_href="",
            archive="",
            recap_title="",  # replaced by linked title below
            recap_range="",
            intro_html="",
            body_html=render_story_body(rec, stories),
            image=image,
            robots="" if on_topic else "noindex,follow",
            json_ld=[
                article_node(
                    type_="NewsArticle",
                    title=title,
                    description=description,
                    canonical=canonical,
                    published=published,
                    base_url=base_url,
                    image=image,
                    source_url=url,
                ),
                breadcrumb_node(
                    base_url, [("Home", "/"), ("Stories", "/"), (title, f"/story/{sid}")]
                ),
            ],
            title_html=(
                f'<h2 class="recap-title story-title"><a href="{escape(safe_http_url(url))}" '
                f'target="_blank" rel="noopener">{escape(title)}</a></h2>'
            ),
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{sid}.html").write_text(html, encoding="utf-8")
        written.add(f"{sid}.html")
        if on_topic:
            sitemap_entries.append((sid, published_dt.date().isoformat() if published_dt else None))
        else:
            noindexed += 1
    prune_orphans(out_dir, SID_HTML_RE, written)
    return sitemap_entries, noindexed


def load_storyline_details() -> list[dict]:
    """Every per-slug storyline timeline file (never pruned; shared links live on).

    Excludes index.json and the agent/scout sidecar subdirectories.
    """
    details = []
    if not STORYLINES_DIR.is_dir():
        return details
    for path in sorted(STORYLINES_DIR.glob("*.json")):
        if path.name == "index.json" or not SLUG_RE.match(path.stem):
            continue
        data = load_json(path)
        if isinstance(data, dict) and data.get("slug") and data.get("days"):
            details.append(data)
    return details


def storyline_member_sids(details: list[dict]) -> set[str]:
    """All story sids that appear in any storyline timeline (keeps them indexable)."""
    sids: set[str] = set()
    for sl in details:
        for day in sl.get("days") or []:
            for it in day.get("items") or []:
                sid = str(it.get("sid") or "")
                if sid:
                    sids.add(sid)
    return sids


def render_storyline_body(sl: dict, story_sids: set[str]) -> str:
    parts = []
    slug = str(sl.get("slug") or "")
    last_updated = str(sl.get("last_updated") or "")
    parts.append(
        '<p class="story-actions"><button id="followBtn" type="button" '
        f'data-slug="{escape(slug)}" data-last-updated="{escape(last_updated)}" '
        'aria-pressed="false">+ Follow this story</button></p>'
    )
    ed = sl.get("editorial") or {}
    tldr = squeeze(ed.get("tldr"))
    whats_new = squeeze(ed.get("whats_new"))
    why = squeeze(ed.get("why_it_matters"))
    if tldr or why or whats_new:
        bits = []
        if tldr:
            bits.append('<p class="tldr-label">TL;DR</p>' f"<p>{escape(tldr)}</p>")
        if whats_new:
            bits.append(f"<p><b>What's new:</b> {escape(whats_new)}</p>")
        if why:
            bits.append(f"<p>💡 {escape(why)}</p>")
        parts.append(f'<div class="intro">{"".join(bits)}</div>')

    for i, day in enumerate(sl.get("days") or []):
        items = day.get("items") or []
        if not items:
            continue
        cards = []
        for it in items:
            href = safe_http_url(it.get("url"))
            sid = story_sid(it.get("url")) if href != "#" else ""
            # Prefer the internal story permalink (hub -> spoke) when we have one.
            title_href = f"/story/{sid}" if sid and sid in story_sids else href
            internal = title_href.startswith("/")
            attrs = "" if internal else ' target="_blank" rel="noopener"'
            meta = []
            if it.get("source"):
                meta.append(f'<span class="badge">{escape(str(it.get("source")))}</span>')
            pub = iso_or_none(it.get("published"))
            if pub:
                d = datetime.fromisoformat(pub)
                meta.append(f'<span class="badge">{escape(d.strftime("%b"))} {d.day}</span>')
            note = squeeze(it.get("editor_note")) or squeeze(it.get("summary_1line"))
            note_html = f'<p class="art-summary">{escape(note)}</p>' if note else ""
            cards.append(
                "<article>"
                f'<h3><a href="{escape(title_href)}"{attrs} data-track="storyline-link">'
                f'{escape(squeeze(it.get("title")) or "Untitled")}</a></h3>'
                f'<div class="art-meta">{"".join(meta)}</div>{note_html}</article>'
            )
        parts.append(
            f'<section class="cat"><h2><span class="count">Day {i + 1}</span> '
            f'{escape(fmt_long_date(str(day.get("date") or "")))}</h2>'
            f'<div class="articles">{"".join(cards)}</div></section>'
        )
    return "".join(parts)


def render_storyline_pages(
    base_url: str, details: list[dict], active_slugs: set[str], story_sids: set[str]
) -> list[tuple[str, str | None]]:
    """Render web/storyline/<slug>.html for every storyline timeline file.

    Active storylines (still in the index window) are returned for the sitemap;
    aged-out threads stay rendered so shared links keep working, just unlisted.
    """
    out_dir = WEB_DIR / "storyline"
    sitemap_entries: list[tuple[str, str | None]] = []
    written: set[str] = set()
    for sl in details:
        slug = str(sl.get("slug") or "")
        if not SLUG_RE.match(slug):
            continue
        label = squeeze(sl.get("label")) or slug
        title = f"{label} — AI storyline"
        ed = sl.get("editorial") or {}
        description = clip(
            squeeze(ed.get("tldr")) or squeeze(sl.get("latest_title")) or label, 250
        )
        canonical = f"{base_url}/storyline/{slug}"
        first_seen = iso_or_none(sl.get("first_seen"))
        last_updated = iso_or_none(sl.get("last_updated"))
        meta_bits = [
            f"{sl.get('item_count', 0)} items",
            f"{sl.get('source_count', 0)} sources",
            f"{sl.get('day_count', 0)} days",
        ]
        html = render_page(
            title=title,
            description=description,
            canonical=canonical,
            published=first_seen,
            h1="📈 AI Storyline",
            meta_line=" · ".join(meta_bits),
            nav_links=[("/storylines", "← All storylines"), ("/", "📰 Live feed"), ("/daily", "🗓️ Daily recap"), ("/rss.xml", "🔔 RSS")],
            json_href=f"/api/storylines?slug={slug}",
            archive="",
            recap_title=label,
            recap_range="",
            intro_html="",
            body_html=render_storyline_body(sl, story_sids),
            json_ld=[
                article_node(
                    type_="NewsArticle",
                    title=title,
                    description=description,
                    canonical=canonical,
                    published=first_seen,
                    base_url=base_url,
                ),
                breadcrumb_node(
                    base_url,
                    [("Home", "/"), ("Storylines", "/storylines"), (label, f"/storyline/{slug}")],
                ),
            ],
            extra_js=STORYLINE_FOLLOW_JS,
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{slug}.html").write_text(html, encoding="utf-8")
        written.add(f"{slug}.html")
        if slug in active_slugs:
            lastmod = (last_updated or first_seen or "")[:10] or None
            sitemap_entries.append((slug, lastmod))
    prune_orphans(out_dir, SLUG_HTML_RE, written)
    sitemap_entries.sort(key=lambda t: t[1] or "", reverse=True)
    return sitemap_entries


def prune_orphans(out_dir: Path, html_re: re.Pattern, keep: set[str]) -> None:
    if not out_dir.is_dir():
        return
    for path in out_dir.glob("*.html"):
        if html_re.match(path.name) and path.name not in keep:
            path.unlink()
            print(f"pruned stale page: {path.relative_to(ROOT)}")


def week_end_date(week_id: str) -> str | None:
    """End (Sunday) of an ISO week id 'YYYY-Www', for sitemap lastmod."""
    m = re.match(r"^(\d{4})-W(\d{2})$", str(week_id))
    if not m:
        return None
    try:
        return date.fromisocalendar(int(m.group(1)), int(m.group(2)), 7).isoformat()
    except ValueError:
        return None


def write_sitemap(
    base_url: str,
    days: list[str],
    weeks: list[str],
    stories: list[tuple[str, str | None]] | None = None,
    storylines: list[tuple[str, str | None]] | None = None,
) -> None:
    today = datetime.now(timezone.utc).date().isoformat()
    entries: list[tuple[str, str | None, str | None]] = [
        (f"{base_url}/", today, "hourly"),
        (f"{base_url}/daily", today, "daily"),
        (f"{base_url}/weekly", today, "weekly"),
        (f"{base_url}/storylines", today, "daily"),
        (f"{base_url}/voices", today, "monthly"),
    ]
    entries += [(f"{base_url}/daily/{d}", d, None) for d in days]
    # Weekly recaps: lastmod = the week's end date (Sunday) when derivable.
    for w in weeks:
        entries.append((f"{base_url}/weekly/{w}", week_end_date(w), None))
    entries += [
        (f"{base_url}/storyline/{slug}", lastmod, "daily")
        for slug, lastmod in storylines or []
    ]
    entries += [(f"{base_url}/story/{sid}", lastmod, None) for sid, lastmod in stories or []]

    rows = []
    for loc, lastmod, changefreq in entries:
        parts = [f"<loc>{escape(loc)}</loc>"]
        if lastmod:
            parts.append(f"<lastmod>{escape(lastmod)}</lastmod>")
        if changefreq:
            parts.append(f"<changefreq>{escape(changefreq)}</changefreq>")
        rows.append("  <url>" + "".join(parts) + "</url>")
    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(rows)
        + "\n</urlset>\n"
    )
    (WEB_DIR / "sitemap.xml").write_text(xml, encoding="utf-8")


def write_robots(base_url: str) -> None:
    (WEB_DIR / "robots.txt").write_text(
        f"User-agent: *\nAllow: /\n\nSitemap: {base_url}/sitemap.xml\n", encoding="utf-8"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base-url", default=DEFAULT_BASE_URL, help="public site origin for canonical/sitemap URLs")
    args = ap.parse_args()
    base_url = args.base_url.rstrip("/")

    stories = load_store()
    story_sids = set(stories)

    storyline_details = load_storyline_details()
    index = load_json(STORYLINES_DIR / "index.json") or {}
    active_slugs = {
        str(s.get("slug"))
        for s in (index.get("storylines") or [])
        if isinstance(s, dict) and s.get("slug")
    }
    member_sids = storyline_member_sids(storyline_details)

    days = render_daily_pages(base_url, story_sids)
    weeks = render_weekly_pages(base_url, story_sids)
    story_pages, noindexed = render_story_pages(base_url, stories, member_sids)
    storyline_pages = render_storyline_pages(
        base_url, storyline_details, active_slugs, story_sids
    )
    write_sitemap(base_url, days, weeks, story_pages, storyline_pages)
    write_robots(base_url)
    print(
        f"static pages rendered: {len(days)} daily, {len(weeks)} weekly, "
        f"{len(story_pages) + noindexed} story ({noindexed} noindex), "
        f"{len(storyline_details)} storyline ({len(storyline_pages)} active) "
        "-> web/daily/, web/weekly/, web/story/, web/storyline/"
    )
    n_urls = 5 + len(days) + len(weeks) + len(story_pages) + len(storyline_pages)
    print(f"sitemap: web/sitemap.xml ({n_urls} urls), robots: web/robots.txt")
    if not days and not weeks and not story_pages and not storyline_pages:
        print("warning: no recaps or stories found; nothing rendered", file=sys.stderr)


if __name__ == "__main__":
    main()
