"""Render recaps + story permalinks to static HTML + sitemap for SEO/previews.

The /daily and /weekly pages are client-rendered JS shells, so crawlers and
link unfurlers see "Loading…" instead of content. This script turns the recap
JSON the pipeline already commits (``data/daily/<date>.json``,
``data/weekly/<week>.json``) and the durable story store
(``data/stories/<YYYY-MM>.json``, see ``pipeline/story_store.py``) into fully
static, indexable pages:

- ``web/daily/<date>.html``    served at ``/daily/<date>``
- ``web/weekly/<week>.html``   served at ``/weekly/<week>``
- ``web/story/<sid>.html``     served at ``/story/<sid>``
- ``web/storyline/<slug>.html`` served at ``/storyline/<slug>``
- ``web/sitemap.xml``          served at ``/sitemap.xml``
- ``web/robots.txt``           served at ``/robots.txt``

Story pages are the durable landing target for shares (``api/share.js``
redirects there) and give every story that made the published feed an
indexable page with internal links (related stories, recap pages), so search
and share traffic land on llm-digest.com instead of expiring with feed
retention.

Storyline pages are the SEO surface for the "what happened next" threads: one
static page per timeline file in ``data/storylines/`` (those are never pruned,
so shared links keep working), with the agent-written editorial overlay and the
day-by-day item list rendered server-side. A minimal Follow button mirrors the
localStorage contract of the dynamic ``web/storyline.html`` shell.

Each page carries a real <title>, meta description, canonical URL, Open
Graph/Twitter cards (defaulting to the branded ``/og-default.png`` card),
NewsArticle + BreadcrumbList JSON-LD, a favicon, and RSS autodiscovery — and
mirrors the markup and styles of the dynamic pages so the reader experience is
identical.

Off-topic story pages (no AI/platform signal, not a release/paper/research item
and not part of a storyline; see ``is_on_topic``) — and genuinely thin pages
that have no body content and aren't part of a storyline — are still rendered
so shared links resolve, but get ``robots=noindex,follow`` and are kept out of
the sitemap to protect topical authority. Storyline members always carry an
up-link to their thread, so they stay substantive (and indexable). A summary
that merely echoes the title is treated as no content (it would render the
title twice), and the meta/OG description falls back to a synthesized line
rather than repeating the headline.

Story bodies prefer the concise ``summary_1line`` produced by ranking; raw RSS
summaries are capped fallbacks, not flattened article bodies.

Stale pages whose recap/story/storyline JSON no longer exists are pruned.

Stdlib only, like the rest of the recap tooling. Run after rebuilding the
recap indexes (build_daily_index.py / build_weekly_index.py do this
automatically):

    python pipeline/render_static_pages.py [--base-url https://example.com]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from datetime import date, datetime, timezone
from html import escape
from pathlib import Path
from urllib.parse import quote, urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_storylines import WEAK as STORYLINE_WEAK, title_tokens  # noqa: E402
from story_store import load_store, parse_dt, story_sid  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DAILY_DIR = ROOT / "data" / "daily"
WEEKLY_DIR = ROOT / "data" / "weekly"
STORYLINES_DIR = ROOT / "data" / "storylines"
WIKI_DIR = ROOT / "data" / "wiki"
WEB_DIR = ROOT / "web"

DEFAULT_BASE_URL = os.environ.get("SITE_BASE_URL", "https://www.llm-digest.com")
SITE_NAME = "LLM Digest"
# Branded social card + publisher logo, generated by scripts/make_og_assets.py.
DEFAULT_OG_IMAGE = "/og-default.png"
LOGO_PATH = "/logo.png"

DATE_FILE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}\.json$")
WEEK_FILE_RE = re.compile(r"^\d{4}-W\d{2}\.json$")
DATE_HTML_RE = re.compile(r"^\d{4}-\d{2}-\d{2}\.html$")
WEEK_HTML_RE = re.compile(r"^\d{4}-W\d{2}\.html$")
SID_HTML_RE = re.compile(r"^[0-9a-f]{16}\.html$")
SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,80}$")
SLUG_HTML_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,80}\.html$")

RELATED_STORIES_MAX = 4
STORY_BRIEF_MAX_CHARS = 320
MECHANICAL_WHY_PREFIXES = ("Matches feed focus:",)

# Topical-authority gate: the feed lets through occasional off-topic posts from
# otherwise-relevant sources (e.g. a frontier lab's consumer/PR announcement).
# Giving those a thin, indexable permalink dilutes our "AI platform engineer"
# topical authority, so they get robots=noindex,follow (link equity still flows
# to related stories) and are kept out of the sitemap. A story is on-topic when
# any AI/platform term appears in its title/summary, OR it is a release/paper/
# research item, OR it belongs to a storyline — conservative by design so we
# only suppress obvious noise. Keep AI_TERMS roughly in sync with
# config/profile.yaml `platform_keywords`.
AI_TERMS = frozenset(
    {
        "ai", "a.i.", "llm", "llms", "gpt", "claude", "gemini", "llama", "mistral",
        "model", "models", "agent", "agents", "agentic", "ml", "neural", "transformer",
        "transformers", "diffusion", "embedding", "embeddings", "rag", "fine-tune",
        "fine-tuning", "finetuning", "inference", "training", "pretraining", "prompt",
        "prompting", "token", "tokens", "context window", "mcp", "openai", "anthropic",
        "deepmind", "hugging face", "huggingface", "vllm", "tensor", "gpu", "cuda",
        # config/profile.yaml platform_keywords
        "serving", "latency", "throughput", "quantization", "eval", "evals",
        "observability", "orchestration", "kubernetes", "triton", "tgi", "benchmark",
        "context", "knowledge", "memory", "retrieval", "interoperab", "tool use",
    }
)
ON_TOPIC_TYPES = frozenset({"release", "paper", "research"})

# Friendly publisher names for the contentless-story framing line (the story
# record only carries the internal source id). Falls back to the source domain.
SOURCE_LABELS = {
    "anthropic_newsroom": "Anthropic",
    "anthropic_research": "Anthropic Research",
    "anthropic_engineering": "Anthropic Engineering",
    "claude_blog": "the Claude blog",
    "huggingface_blog": "the Hugging Face blog",
    "langchain_blog": "the LangChain blog",
    "google_ai_blog": "the Google AI blog",
    "google_deepmind_blog": "the Google DeepMind blog",
    "openai_blog": "the OpenAI blog",
}


def source_label(rec: dict, url: str) -> str:
    """Human-readable publisher name for a story, for prose framing."""
    src = str(rec.get("source") or "")
    return SOURCE_LABELS.get(src) or source_domain(url)

# Same look as web/daily.html / web/weekly.html so static and dynamic pages
# are indistinguishable to readers. Keep in sync when restyling those shells.
PAGE_CSS = """\
    html { font-size: 16px; -webkit-text-size-adjust: 100%; text-size-adjust: 100%; }
    :root, html[data-theme="light"] {
      --bg: #ffffff; --fg: #1a1a1a; --card: #ffffff; --border: #e5e5e5; --accent: #2563eb; --muted: #6b7280;
    }
    html[data-theme="dark"] {
      --bg: #15171c; --fg: #e8e8ea; --card: #1e2128; --border: #34373f; --accent: #5b8def; --muted: #9aa0aa;
    }
    body { margin: 0; line-height: 1.5; overflow-x: hidden; background: var(--bg); color: var(--fg); }
    *, *::before, *::after { box-sizing: border-box; }
    button, input, select, textarea { color: inherit; background: var(--card); border-color: var(--border); }
    a { color: var(--accent); }
    main { width: 100%; max-width: 860px; margin: 1rem auto; padding: 0 0.9rem 3rem; overflow-x: clip; }
    header { margin-bottom: 1rem; }
    .topbar { display: flex; align-items: center; justify-content: space-between; gap: 0.75rem; }
    .topbar h1 { margin: 0; font-size: 1.5rem; line-height: 1.2; overflow-wrap: anywhere; }
    menu { display: flex; flex-wrap: wrap; gap: 0.75rem; padding: 0; margin: 0.75rem 0 0; align-items: center; }
    .muted { color: var(--muted); }
    .recap-title { font-size: 1.7rem; margin: 1.2rem 0 0.2rem; line-height: 1.25; }
    .recap-range { color: var(--muted); margin: 0 0 1rem; font-size: 0.98rem; }
    .intro { font-size: 1.05rem; background: var(--card); border: 1px solid var(--border);
      border-radius: 12px; padding: 1rem 1.1rem; margin: 0 0 1.5rem; }
    .intro p { margin: 0 0 0.75rem; }
    .intro p:last-child { margin-bottom: 0; }
    .tldr { margin: 0 0 1rem; padding: 0 0 0.9rem; border-bottom: 1px solid var(--border); }
    .tldr-label { text-transform: uppercase; letter-spacing: 0.05em; font-size: 0.72rem;
      font-weight: 600; color: var(--muted); margin: 0 0 0.55rem; }
    .tldr ul { margin: 0; padding-left: 1.15rem; display: flex; flex-direction: column; gap: 0.4rem; }
    .tldr li { font-size: 0.95rem; line-height: 1.45; }
    .toc { display: flex; flex-wrap: wrap; gap: 0.4rem; margin: 0 0 1.5rem; }
    .toc a { font-size: 0.9rem; padding: 0.3rem 0.7rem; border: 1px solid var(--border);
      border-radius: 999px; text-decoration: none; }
    .toc a:hover { border-color: var(--accent); }
    .cat { margin: 0 0 2rem; scroll-margin-top: 1rem; }
    .cat h2 { font-size: 1.25rem; margin: 0 0 0.25rem; display: flex; align-items: baseline; gap: 0.5rem; }
    .cat h2 .count { font-size: 0.85rem; color: var(--muted); font-weight: 400; }
    .cat-summary { color: var(--fg); opacity: 0.9; margin: 0 0 0.9rem; }
    .articles { display: flex; flex-direction: column; gap: 0.7rem; }
    article { border: 1px solid var(--border); border-radius: 10px; padding: 0.8rem 0.9rem; background: var(--card); }
    article h3 { margin: 0 0 0.3rem; font-size: 1.02rem; line-height: 1.35; }
    article h3 a { text-decoration: none; }
    article h3 a:hover { text-decoration: underline; }
    .art-meta { display: flex; flex-wrap: wrap; gap: 0.4rem; align-items: center; margin-bottom: 0.3rem; }
    .badge { font-size: 0.72rem; padding: 0.1rem 0.5rem; font-weight: 500;
      border: 1px solid color-mix(in srgb, var(--accent) 35%, transparent);
      border-radius: 999px; color: var(--accent);
      background: color-mix(in srgb, var(--accent) 14%, var(--card)); white-space: nowrap; }
    .art-summary { margin: 0.1rem 0 0; font-size: 0.95rem; }
    .archive { margin-left: auto; }
    footer { margin-top: 2rem; color: var(--muted); font-size: 0.85rem; }
    .story-title a { text-decoration: none; color: inherit; }
    .story-title a:hover { text-decoration: underline; }
    .story-lead { display: grid; grid-template-columns: minmax(0, 1fr) 160px;
      gap: 1rem; align-items: center; background: var(--card); border: 1px solid var(--border);
      border-radius: 12px; padding: 1rem 1.1rem; margin: 0 0 1.2rem; }
    .story-lead p { margin: 0; }
    .story-img { width: 160px; height: 112px; object-fit: cover;
      border-radius: 9px; border: 1px solid var(--border); }
    .story-summary { font-size: 1.02rem; line-height: 1.55; margin: 0; }
    .story-framing { font-size: 1.02rem; margin: 0 0 1.2rem; }
    .chips { display: flex; flex-wrap: wrap; gap: 0.4rem; margin: 0 0 1.2rem; clear: both; }
    .story-actions { display: flex; flex-wrap: wrap; gap: 0.6rem; margin: 0 0 1.6rem; clear: both; }
    .story-actions a, .story-actions button { font-family: inherit; font-size: 0.92rem;
      min-height: 44px; padding: 0.45rem 0.95rem; display: inline-flex; align-items: center;
      border: 1px solid var(--border); border-radius: 10px; text-decoration: none;
      background: var(--card); color: var(--fg); cursor: pointer; }
    .story-actions a.primary, .story-actions button.primary { border-color: var(--accent);
      color: var(--accent); background: color-mix(in srgb, var(--accent) 12%, var(--card)); }
    .story-actions a:hover, .story-actions button:hover { border-color: var(--accent); }
    .story-actions button[aria-pressed="true"] { border-color: var(--accent);
      background: color-mix(in srgb, var(--accent) 22%, var(--card)); color: var(--accent); }
    @media (max-width: 560px) {
      .story-lead { grid-template-columns: 1fr; }
      .story-img { width: 100%; height: auto; max-height: 220px; }
    }
    .covered { margin: 0 0 1.6rem; }
    .covered ul { margin: 0.4rem 0 0; padding-left: 1.15rem; }
    .covered li { margin: 0.25rem 0; font-size: 0.95rem; }
"""

THEME_BOOT_JS = """\
    (function () {
      var t = localStorage.getItem('theme') || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
      document.documentElement.setAttribute('data-theme', t);
    })();
"""

PAGE_JS = """\
    (function () {
      function applyTheme(theme) {
        document.documentElement.setAttribute('data-theme', theme);
        localStorage.setItem('theme', theme);
        var btn = document.getElementById('themeToggle');
        if (btn) btn.textContent = theme === 'dark' ? '☀️ Light' : '🌙 Dark';
      }
      var btn = document.getElementById('themeToggle');
      if (btn) {
        applyTheme(document.documentElement.getAttribute('data-theme') || 'light');
        btn.addEventListener('click', function () {
          var now = document.documentElement.getAttribute('data-theme') || 'light';
          applyTheme(now === 'dark' ? 'light' : 'dark');
        });
      }
      var sel = document.getElementById('archive');
      if (sel) sel.addEventListener('change', function () { window.location.href = sel.value; });
    })();
"""

# Follow button for static storyline pages. Mirrors the localStorage contract
# in web/storyline.html (FOLLOWS_KEY ai_feed_storyline_follows_v1) so a follow
# made on a static page is recognized by the dynamic /storylines list and vice
# versa. PostHog capture is intentionally omitted (optional/secret-gated).
STORYLINE_FOLLOW_JS = """\
    (function () {
      var KEY = 'ai_feed_storyline_follows_v1';
      var btn = document.getElementById('followBtn');
      if (!btn) return;
      function load() { try { return JSON.parse(localStorage.getItem(KEY) || '{}'); } catch (e) { return {}; } }
      function save(f) { try { localStorage.setItem(KEY, JSON.stringify(f)); } catch (e) {} }
      var slug = btn.dataset.slug, lu = btn.dataset.lastUpdated || '';
      function paint() {
        var on = !!load()[slug];
        btn.setAttribute('aria-pressed', on ? 'true' : 'false');
        btn.textContent = on ? '\\u2713 Following' : '+ Follow this story';
      }
      paint();
      btn.addEventListener('click', function () {
        var f = load();
        if (f[slug]) { delete f[slug]; }
        else { f[slug] = { followed_at: new Date().toISOString(), seen_updated: lu }; }
        save(f);
        paint();
      });
    })();
"""

# Arc view for /storyline/<slug>. Theme-aware (uses the page's CSS variables;
# tone colors are semantic mid-tones that read on both light and dark). Scoped
# under .sl so it never leaks into recap/story pages. See render_storyline_body.
STORYLINE_ARC_CSS = """\
    /* Pin the storyline page to the prototype's true GitHub-dark palette (dark
       theme only); light theme keeps the site defaults. Scoped to this page
       because extra_css is injected per-page. */
    html[data-theme="dark"] { --bg:#0d1117; --card:#0f141b; --border:#21262d;
      --accent:#58a6ff; --muted:#8b949e; --fg:#e6edf3; }
    .sl-hero { display:flex; align-items:center; gap:1rem; flex-wrap:wrap; margin:1.4rem 0 0.5rem; }
    .sl-hero .recap-title { margin:0; font-size:2.15rem; font-weight:700; letter-spacing:-0.02em; line-height:1.1; }
    .sl-hero #followBtn { font-family:inherit; font-size:0.85rem; font-weight:500; min-height:0;
      padding:0.5rem 0.9rem; border-radius:9px; cursor:pointer; color:var(--accent); background:transparent;
      border:1px solid color-mix(in srgb,var(--accent) 45%,var(--border)); }
    .sl-hero #followBtn[aria-pressed="true"] { background:color-mix(in srgb,var(--accent) 16%,var(--card)); }
    :root { --t-launch:#2ea043; --t-rising:var(--muted); --t-turn:#e5534b;
      --t-now:#d9a521; --t-resolved:var(--accent); --t-neutral:var(--border); }
    .sl-status { border:1px solid var(--border); border-radius:12px;
      padding:0.85rem 1.05rem; margin:0 0 1.4rem; background:var(--card); }
    .sl-status.tone-turn, .sl-status.tone-alert { border-color:color-mix(in srgb,var(--t-turn) 45%,var(--border)); background:color-mix(in srgb,var(--t-turn) 7%,var(--card)); }
    .sl-status.tone-now { border-color:color-mix(in srgb,var(--t-now) 45%,var(--border)); background:color-mix(in srgb,var(--t-now) 9%,var(--card)); }
    .sl-status.tone-launch, .sl-status.tone-resolved { border-color:color-mix(in srgb,var(--t-launch) 40%,var(--border)); background:color-mix(in srgb,var(--t-launch) 7%,var(--card)); }
    .sl-status-head { display:flex; align-items:center; gap:0.5rem; flex-wrap:wrap; margin-bottom:0.45rem; }
    .sl-dot { width:9px; height:9px; border-radius:50%; background:var(--t-now); flex:none; }
    .sl-status.tone-turn .sl-dot, .sl-status.tone-alert .sl-dot, .sl-status.tone-now .sl-dot { animation:slPulse 2.4s infinite; }
    .sl-status.tone-turn .sl-dot, .sl-status.tone-alert .sl-dot { background:var(--t-turn); }
    .sl-status.tone-launch .sl-dot, .sl-status.tone-resolved .sl-dot { background:var(--t-launch); }
    @keyframes slPulse { 0%,100%{box-shadow:0 0 0 0 color-mix(in srgb,var(--t-now) 55%,transparent);} 70%{box-shadow:0 0 0 5px transparent;} }
    .sl-state { font-family:ui-monospace,monospace; font-size:0.72rem; letter-spacing:.06em;
      text-transform:uppercase; font-weight:700; color:var(--t-now); }
    .sl-status.tone-turn .sl-state, .sl-status.tone-alert .sl-state { color:var(--t-turn); }
    .sl-status.tone-launch .sl-state, .sl-status.tone-resolved .sl-state { color:var(--t-launch); }
    .sl-status-meta { font-size:0.8rem; color:var(--muted); }
    .sl-status-detail { margin:0; font-size:0.98rem; line-height:1.55; }
    .sl-tabs { display:flex; align-items:center; gap:1.2rem; border-bottom:1px solid var(--border); margin:0 0 1.4rem; }
    .sl-tab { font:inherit; font-size:0.9rem; font-weight:600; color:var(--muted);
      background:none; border:none; border-bottom:2px solid transparent; padding:0 0 0.6rem; cursor:pointer; }
    .sl-tab.is-active { color:var(--fg); border-bottom-color:var(--accent); }
    .sl-tab-note { margin-left:auto; font-family:ui-monospace,monospace; font-size:0.7rem; color:var(--muted); padding-bottom:0.6rem; }
    .sl-rail-label, .sl-watch-label { font-family:ui-monospace,monospace; font-size:0.66rem;
      letter-spacing:.08em; text-transform:uppercase; color:var(--muted); margin:0 0 0.5rem; }
    .sl-rail { display:flex; gap:2px; height:11px; border-radius:6px; overflow:hidden; margin:0 0 0.4rem; }
    .sl-rail-seg { flex:1; min-width:8px; border-radius:3px; }
    .sl-rail-ends { display:flex; justify-content:space-between; font-family:ui-monospace,monospace;
      font-size:0.7rem; color:var(--muted); margin:0 0 1.8rem; }
    .tone-launch-bg{background:var(--t-launch);} .tone-rising-bg{background:var(--t-rising);}
    .tone-turn-bg{background:var(--t-turn);} .tone-now-bg{background:var(--t-now);}
    .tone-resolved-bg{background:var(--t-resolved);} .tone-neutral-bg{background:var(--t-neutral);}
    .tone-launch-fg{color:var(--t-launch);} .tone-rising-fg{color:var(--t-rising);}
    .tone-turn-fg{color:var(--t-turn);} .tone-now-fg{color:var(--t-now);}
    .tone-resolved-fg{color:var(--t-resolved);} .tone-neutral-fg{color:var(--muted);}
    .sl-track { display:flex; gap:2px; height:13px; border-radius:7px; overflow:hidden; margin:0 0 0.5rem; }
    .sl-track-seg { border-radius:3px; }
    .sl-track-ends { display:flex; justify-content:space-between; font-family:ui-monospace,monospace;
      font-size:0.72rem; margin:0 0 1.9rem; }
    .sl-spine { position:relative; padding-left:2rem; }
    .sl-spine::before { content:""; position:absolute; left:6px; top:6px; bottom:6px; width:2px; background:var(--border); }
    .sl-beat { position:relative; margin:0 0 1.5rem; }
    .sl-beat > summary { list-style:none; cursor:pointer; }
    .sl-beat > summary::-webkit-details-marker { display:none; }
    .sl-node { position:absolute; left:-1.72rem; top:3px; width:14px; height:14px; border-radius:50%;
      background:var(--bg); border:2px solid var(--t-neutral); }
    .sl-beat.tone-launch .sl-node{border-color:var(--t-launch);}
    .sl-beat.tone-rising .sl-node{border-color:var(--t-rising);}
    .sl-beat.tone-now .sl-node{border-color:var(--t-now);}
    .sl-beat.tone-resolved .sl-node{border-color:var(--t-resolved);}
    .sl-beat.tone-turn .sl-node{ left:-1.85rem; top:1px; width:20px; height:20px; border-width:3px;
      border-color:var(--t-turn); box-shadow:0 0 0 5px color-mix(in srgb,var(--t-turn) 14%,transparent); }
    .sl-kicker { font-family:ui-monospace,monospace; font-size:0.7rem; color:var(--muted); margin:0 0 0.25rem; }
    .sl-beat.tone-launch .sl-kicker{color:var(--t-launch);} .sl-beat.tone-now .sl-kicker{color:var(--t-now);}
    .sl-beat.tone-turn .sl-kicker{color:var(--t-turn); font-weight:700;}
    .sl-beat-title { font-size:1.02rem; font-weight:600; line-height:1.35; }
    .sl-beat.tone-turn .sl-beat-title { font-size:1.12rem; font-weight:700; }
    .sl-beat-sum { font-size:0.92rem; color:var(--fg); opacity:0.82; margin-top:0.35rem; line-height:1.5; }
    .sl-ok { color:var(--t-launch); }
    .sl-show { font-size:0.8rem; color:var(--muted); margin-top:0.4rem; }
    .sl-show-link { color:var(--accent); }
    .sl-cards { display:flex; flex-direction:column; gap:0.6rem; margin-top:0.8rem; }
    .sl-card.sl-card-turn { border-color:color-mix(in srgb,var(--t-turn) 45%,var(--border));
      background:color-mix(in srgb,var(--t-turn) 7%,var(--card)); }
    .sl-card h3 a { color:var(--accent); }
    .sl-watch { border:1px solid var(--border); border-radius:12px; padding:0.95rem 1.1rem; margin:1.8rem 0 0; }
    .sl-watch ul { margin:0; padding-left:1.1rem; display:flex; flex-direction:column; gap:0.5rem; }
    .sl-watch li { font-size:0.95rem; line-height:1.45; }
    .sl-watch li::marker { color:var(--t-now); }
    .sl-take { margin-top:0.9rem; padding-top:0.85rem; border-top:1px solid var(--border); font-size:0.93rem; line-height:1.55; }
    .sl-agents { border:1px solid var(--border); border-radius:12px; padding:0.85rem 1.1rem; margin:1.4rem 0 0; }
    .sl-agent-row { display:flex; gap:1.4rem; flex-wrap:wrap; font-family:ui-monospace,monospace; font-size:0.78rem; color:var(--muted); }
    .sl-agent-row b { font-weight:600; }
    .sl-agent-row .a-scout, .sl-agent-row .a-editor { color:var(--accent); }
    .sl-agent-row .a-check { color:var(--t-launch); }
    .sl-agent-row .a-watch { color:var(--t-now); }
    .sl-note { margin-top:1.6rem; font-size:0.84rem; line-height:1.6; color:var(--muted); }
    [data-sl-view][hidden] { display:none; }
"""

# Arc/Timeline tab toggle for the storyline page (progressive enhancement — the
# Arc view is shown by default; without JS both views are simply visible).
STORYLINE_ARC_JS = """\
    (function () {
      var tabs = document.querySelectorAll('.sl-tab');
      if (!tabs.length) return;
      var views = document.querySelectorAll('[data-sl-view]');
      function show(view) {
        views.forEach(function (v) { v.hidden = v.getAttribute('data-sl-view') !== view; });
        tabs.forEach(function (t) { t.classList.toggle('is-active', t.getAttribute('data-view') === view); });
      }
      tabs.forEach(function (t) {
        t.addEventListener('click', function () { show(t.getAttribute('data-view')); });
      });
      show('arc');
    })();
"""


def load_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def squeeze(text: str) -> str:
    return " ".join(str(text or "").split())


def clip(text: str, limit: int) -> str:
    text = squeeze(text)
    if len(text) <= limit:
        return text
    cut = text[: limit - 1].rsplit(" ", 1)[0]
    return cut + "…"


def story_why(rec: dict) -> str:
    """Reader-facing rationale only; ranking diagnostics belong in topic chips."""
    why = squeeze(rec.get("why_it_matters"))
    if any(why.startswith(prefix) for prefix in MECHANICAL_WHY_PREFIXES):
        return ""
    return why


def story_brief(rec: dict) -> str:
    """Concise permalink copy, never a flattened full RSS/article body."""
    title_cf = squeeze(rec.get("title")).casefold()
    for candidate in (rec.get("summary_1line"), rec.get("summary")):
        brief = squeeze(candidate)
        if brief and brief.casefold() != title_cf:
            return clip(brief, STORY_BRIEF_MAX_CHARS)
    return ""


def intro_paragraphs(intro) -> list[str]:
    if isinstance(intro, list):
        return [squeeze(p) for p in intro if squeeze(p)]
    return [squeeze(p) for p in re.split(r"\n{2,}", str(intro or "")) if squeeze(p)]


def recap_description(recap: dict) -> str:
    """Meta/OG description: first highlight(s) if present, else the intro."""
    highlights = [squeeze(h) for h in recap.get("highlights") or [] if squeeze(h)]
    if highlights:
        return clip(" ".join(highlights), 250)
    paras = intro_paragraphs(recap.get("intro"))
    return clip(paras[0] if paras else "", 250)


def iso_or_none(value) -> str | None:
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00")).isoformat()
    except Exception:
        return None


def fmt_long_date(day_id: str) -> str:
    """e.g. 'Wednesday, Jun 10, 2026' (matches the dynamic page header)."""
    try:
        d = date.fromisoformat(day_id)
    except Exception:
        return str(day_id)
    return f"{d.strftime('%A')}, {d.strftime('%b')} {d.day}, {d.year}"


def safe_http_url(value) -> str:
    s = str(value or "").strip()
    return s if s.startswith("http://") or s.startswith("https://") else "#"


def render_intro(recap: dict) -> str:
    paras = intro_paragraphs(recap.get("intro"))
    highlights = [squeeze(h) for h in recap.get("highlights") or [] if squeeze(h)]
    if not paras and not highlights:
        return ""
    tldr = ""
    if highlights:
        items = "".join(f"<li>{escape(h)}</li>" for h in highlights)
        tldr = (
            '<div class="tldr"><p class="tldr-label">In 30 seconds</p>'
            f"<ul>{items}</ul></div>"
        )
    body = "".join(f"<p>{escape(p)}</p>" for p in paras)
    return f'<div class="intro">{tldr}{body}</div>'


def render_categories(recap: dict, track: str, story_sids: set[str] | None = None) -> str:
    cats = [c for c in recap.get("categories") or [] if isinstance(c, dict)]
    toc = ""
    if len(cats) > 1:
        links = "".join(
            f'<a href="#{escape(str(c.get("slug") or c.get("name") or ""))}">'
            f'{escape(str(c.get("name") or ""))} ({len(c.get("articles") or [])})</a>'
            for c in cats
        )
        toc = f'<nav class="toc">{links}</nav>'

    sections = []
    for c in cats:
        arts = []
        for a in c.get("articles") or []:
            if not isinstance(a, dict):
                continue
            href = safe_http_url(a.get("url"))
            pub = iso_or_none(a.get("published"))
            pub_badge = ""
            if pub:
                d = datetime.fromisoformat(pub)
                pub_badge = f'<span class="badge">{escape(d.strftime("%b"))} {d.day}</span>'
            src_badge = (
                f'<span class="badge">{escape(str(a.get("source")))}</span>'
                if a.get("source")
                else ""
            )
            # Internal link to the story permalink page (hub -> spoke), kept
            # alongside the external title link so titles still go to sources.
            sid = story_sid(a.get("url")) if href != "#" else ""
            detail_link = (
                f'<a class="badge" href="/story/{sid}" data-track="story-link">Details</a>'
                if story_sids and sid in story_sids
                else ""
            )
            summary = (
                f'<p class="art-summary">{escape(squeeze(a.get("summary")))}</p>'
                if squeeze(a.get("summary"))
                else ""
            )
            arts.append(
                "<article>"
                f'<h3><a href="{escape(href)}" target="_blank" rel="noopener" data-track="{track}">'
                f'{escape(squeeze(a.get("title")) or "Untitled")}</a></h3>'
                f'<div class="art-meta">{src_badge}{pub_badge}{detail_link}</div>'
                f"{summary}</article>"
            )
        n = len(arts)
        cat_summary = (
            f'<p class="cat-summary">{escape(squeeze(c.get("summary")))}</p>'
            if squeeze(c.get("summary"))
            else ""
        )
        sections.append(
            f'<section class="cat" id="{escape(str(c.get("slug") or c.get("name") or ""))}">'
            f'<h2>{escape(str(c.get("name") or ""))} <span class="count">{n} item{"" if n == 1 else "s"}</span></h2>'
            f'{cat_summary}<div class="articles">{"".join(arts)}</div></section>'
        )
    return toc + "".join(sections)


def render_archive_select(options: list[tuple[str, str]], current: str, label: str) -> str:
    """Static archive picker; options are (href, text) pairs, newest first."""
    opts = "".join(
        f'<option value="{escape(href)}"{" selected" if href == current else ""}>{escape(text)}</option>'
        for href, text in options
    )
    return (
        f'<label class="archive muted">{escape(label)} '
        f'<select id="archive" aria-label="Choose {escape(label.lower())}">{opts}</select></label>'
    )


def publisher_node(base_url: str) -> dict:
    """schema.org Organization for the publisher, with a logo (rich-result req)."""
    return {
        "@type": "Organization",
        "name": SITE_NAME,
        "url": base_url + "/",
        "logo": {"@type": "ImageObject", "url": base_url + LOGO_PATH},
    }


def breadcrumb_node(base_url: str, trail: list[tuple[str, str]]) -> dict:
    """BreadcrumbList from (name, path) pairs, e.g. [('Home','/'),('Daily','/daily')]."""
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": i + 1,
                "name": name,
                "item": base_url + path,
            }
            for i, (name, path) in enumerate(trail)
        ],
    }


def article_node(
    *,
    type_: str,
    title: str,
    description: str,
    canonical: str,
    published: str | None,
    base_url: str,
    image: str = "",
    source_url: str = "",
) -> dict:
    """schema.org Article/NewsArticle node for a recap, story, or storyline."""
    node: dict = {
        "@type": type_,
        "headline": title,
        "description": description,
        "datePublished": published,
        "mainEntityOfPage": canonical,
        "publisher": publisher_node(base_url),
    }
    if image.startswith(("http://", "https://")):
        node["image"] = image
    if source_url.startswith(("http://", "https://")):
        node["isBasedOn"] = source_url  # the original we summarize/link to
    return node


def json_ld_script(nodes: list[dict]) -> str:
    """One <script> carrying a @graph of schema.org nodes (or a single node)."""
    nodes = [n for n in nodes if n]
    if not nodes:
        return ""
    if len(nodes) == 1:
        payload = {"@context": "https://schema.org", **nodes[0]}
    else:
        payload = {"@context": "https://schema.org", "@graph": nodes}
    # Page text must never be able to close the surrounding </script>.
    encoded = json.dumps(payload, ensure_ascii=False).replace("</", "<\\/")
    return f'\n  <script type="application/ld+json">{encoded}</script>'


def render_head(
    *,
    title: str,
    description: str,
    canonical: str,
    published: str | None,
    image: str = "",
    og_type: str = "article",
    robots: str = "",
    json_ld: list[dict] | None = None,
    extra_css: str = "",
) -> str:
    og_published = (
        f'\n  <meta property="article:published_time" content="{escape(published)}" />'
        if published and og_type == "article"
        else ""
    )
    # Fall back to the branded default card so every static page shares with an
    # image. Origin is derived from the canonical URL (which already carries the
    # configured base URL) so a custom --base-url stays consistent.
    if not image.startswith(("http://", "https://")):
        split = urlsplit(canonical)
        if split.scheme and split.netloc:
            image = f"{split.scheme}://{split.netloc}{DEFAULT_OG_IMAGE}"
    has_image = image.startswith(("http://", "https://"))
    og_image = (
        f'\n  <meta property="og:image" content="{escape(image)}" />'
        f'\n  <meta name="twitter:image" content="{escape(image)}" />'
        if has_image
        else ""
    )
    robots_meta = (
        f'\n  <meta name="robots" content="{escape(robots)}" />' if robots else ""
    )
    twitter_card = "summary_large_image" if has_image else "summary"
    ld = json_ld_script(json_ld or [])
    return f"""\
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />{robots_meta}
  <title>{escape(title)} | {escape(SITE_NAME)}</title>
  <meta name="description" content="{escape(description)}" />
  <link rel="canonical" href="{escape(canonical)}" />
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <link rel="icon" href="/favicon-32.png" sizes="32x32" type="image/png" />
  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
  <link rel="manifest" href="/site.webmanifest" />
  <meta property="og:type" content="{escape(og_type)}" />
  <meta property="og:site_name" content="{escape(SITE_NAME)}" />
  <meta property="og:title" content="{escape(title)}" />
  <meta property="og:description" content="{escape(description)}" />
  <meta property="og:url" content="{escape(canonical)}" />{og_published}{og_image}
  <meta name="twitter:card" content="{twitter_card}" />
  <meta name="twitter:title" content="{escape(title)}" />
  <meta name="twitter:description" content="{escape(description)}" />{ld}
  <link rel="alternate" type="application/rss+xml" title="{escape(SITE_NAME)} feed" href="/rss.xml" />
  <link rel="stylesheet" href="https://oat.ink/oat.min.css" />
  <script defer src="/_vercel/speed-insights/script.js"></script>
  <script>
{THEME_BOOT_JS}  </script>
  <style>
{PAGE_CSS}{extra_css}  </style>"""


def render_page(
    *,
    title: str,
    description: str,
    canonical: str,
    published: str | None,
    h1: str,
    meta_line: str,
    nav_links: list[tuple[str, str]],
    json_href: str,
    archive: str,
    recap_title: str,
    recap_range: str,
    intro_html: str,
    body_html: str,
    image: str = "",
    title_html: str = "",
    og_type: str = "article",
    robots: str = "",
    json_ld: list[dict] | None = None,
    extra_js: str = "",
    extra_css: str = "",
) -> str:
    nav = "".join(f'\n        <a href="{escape(h)}" role="button">{escape(t)}</a>' for h, t in nav_links)
    json_link = f'\n        <a href="{escape(json_href)}" role="button">JSON</a>' if json_href else ""
    heading = title_html or f'<h2 class="recap-title">{escape(recap_title)}</h2>'
    range_line = f'<p class="recap-range">{escape(recap_range)}</p>' if recap_range else ""
    return f"""<!doctype html>
<html lang="en">
<head>
{render_head(title=title, description=description, canonical=canonical, published=published, image=image, og_type=og_type, robots=robots, json_ld=json_ld, extra_css=extra_css)}
</head>
<body>
  <main>
    <header>
      <div class="topbar">
        <h1>{h1}</h1>
        <button id="themeToggle" type="button" aria-label="Toggle theme">🌙 Dark</button>
      </div>
      <p id="meta" class="muted">{escape(meta_line)}</p>
      <menu>{nav}{json_link}
        {archive}
      </menu>
    </header>

    <section id="recap">
      {heading}
      {range_line}
      {intro_html}
      {body_html}
    </section>

    <footer>
      Built from the AI SOTA feed. Each item links to its original source. ·
      <a href="/rss.xml">RSS</a>
    </footer>
  </main>
  <script>
{PAGE_JS}{extra_js}  </script>

  <!-- Bubble Buddy mascot: decorative WebGL character, lazy-loaded on idle,
       skipped under prefers-reduced-motion. Never affects initial load. -->
  <script type="module">
    if (!matchMedia('(prefers-reduced-motion: reduce)').matches) {{
      const go = () => import('/mascot/mascot.js').catch(() => {{}});
      'requestIdleCallback' in window ? requestIdleCallback(go, {{ timeout: 5000 }}) : setTimeout(go, 2500);
    }}
  </script>
</body>
</html>
"""


def load_recaps(directory: Path, file_re: re.Pattern, id_field: str) -> list[dict]:
    recaps = []
    if not directory.is_dir():
        return recaps
    for path in sorted(directory.glob("*.json")):
        if not file_re.match(path.name):
            continue
        data = load_json(path)
        if isinstance(data, dict) and data.get(id_field) and data.get("categories"):
            recaps.append(data)
    recaps.sort(key=lambda r: str(r.get(id_field)), reverse=True)
    return recaps


def meta_line_for(recap: dict) -> str:
    cats = recap.get("categories") or []
    total = recap.get("article_count") or sum(len(c.get("articles") or []) for c in cats)
    return f"{total} articles · {len(cats)} categories"


def render_daily_pages(base_url: str, story_sids: set[str] | None = None) -> list[str]:
    recaps = load_recaps(DAILY_DIR, DATE_FILE_RE, "date")
    out_dir = WEB_DIR / "daily"
    archive_options = [
        (f"/daily/{r['date']}", f"{r['date']} · {squeeze(r.get('title'))}") for r in recaps
    ]
    ids = []
    for recap in recaps:
        day = str(recap["date"])
        canonical = f"{base_url}/daily/{day}"
        title = squeeze(recap.get("title")) or f"AI Daily Recap — {day}"
        description = recap_description(recap)
        published = iso_or_none(recap.get("generated_at"))
        html = render_page(
            title=title,
            description=description,
            canonical=canonical,
            published=published,
            h1="📰 AI Daily Recap",
            meta_line=meta_line_for(recap),
            nav_links=[("/", "← Live feed"), ("/storylines", "📈 Storylines"), ("/weekly", "🗓️ Weekly recap"), ("/voices", "🗣️ Voices"), ("/rss.xml", "🔔 RSS")],
            json_href=f"/api/daily?date={day}",
            archive=render_archive_select(archive_options, f"/daily/{day}", "Day"),
            recap_title=squeeze(recap.get("title")) or day,
            recap_range=fmt_long_date(day),
            intro_html=render_intro(recap),
            body_html=render_categories(recap, "daily-link", story_sids),
            json_ld=[
                article_node(
                    type_="NewsArticle",
                    title=title,
                    description=description,
                    canonical=canonical,
                    published=published,
                    base_url=base_url,
                ),
                breadcrumb_node(
                    base_url,
                    [("Home", "/"), ("Daily recaps", "/daily"), (day, f"/daily/{day}")],
                ),
            ],
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{day}.html").write_text(html, encoding="utf-8")
        ids.append(day)
    prune_orphans(out_dir, DATE_HTML_RE, {f"{i}.html" for i in ids})
    return ids


def render_weekly_pages(base_url: str, story_sids: set[str] | None = None) -> list[str]:
    recaps = load_recaps(WEEKLY_DIR, WEEK_FILE_RE, "week")
    out_dir = WEB_DIR / "weekly"
    archive_options = [
        (f"/weekly/{r['week']}", f"{r['week']} · {squeeze(r.get('title'))}") for r in recaps
    ]
    ids = []
    for recap in recaps:
        week = str(recap["week"])
        canonical = f"{base_url}/weekly/{week}"
        recap_range = " – ".join(
            s for s in (str(recap.get("start") or ""), str(recap.get("end") or "")) if s
        )
        title = squeeze(recap.get("title")) or f"AI Weekly Recap — {week}"
        description = recap_description(recap)
        published = iso_or_none(recap.get("generated_at"))
        html = render_page(
            title=title,
            description=description,
            canonical=canonical,
            published=published,
            h1="🗓️ AI Weekly Recap",
            meta_line=meta_line_for(recap),
            nav_links=[("/", "← Live feed"), ("/storylines", "📈 Storylines"), ("/daily", "📰 Daily recap"), ("/voices", "🗣️ Voices"), ("/rss.xml", "🔔 RSS")],
            json_href=f"/api/weekly?week={week}",
            archive=render_archive_select(archive_options, f"/weekly/{week}", "Week"),
            recap_title=squeeze(recap.get("title")) or week,
            recap_range=f"{recap_range} · {week}" if recap_range else week,
            intro_html=render_intro(recap),
            body_html=render_categories(recap, "weekly-link", story_sids),
            json_ld=[
                article_node(
                    type_="NewsArticle",
                    title=title,
                    description=description,
                    canonical=canonical,
                    published=published,
                    base_url=base_url,
                ),
                breadcrumb_node(
                    base_url,
                    [("Home", "/"), ("Weekly recaps", "/weekly"), (week, f"/weekly/{week}")],
                ),
            ],
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{week}.html").write_text(html, encoding="utf-8")
        ids.append(week)
    prune_orphans(out_dir, WEEK_HTML_RE, {f"{i}.html" for i in ids})
    return ids


def story_dt(rec: dict) -> datetime:
    dt = parse_dt(rec.get("published")) or parse_dt(rec.get("first_seen"))
    return dt or datetime.fromtimestamp(0, tz=timezone.utc)


def fmt_story_date(dt: datetime) -> str:
    return f"{dt.strftime('%b')} {dt.day}, {dt.year}"


def source_domain(url: str) -> str:
    try:
        host = urlsplit(url).hostname or ""
    except ValueError:
        host = ""
    return host.removeprefix("www.") or "the source"


def is_on_topic(rec: dict, storyline_sids) -> bool:
    """Whether a story deserves an indexable permalink (see AI_TERMS docstring).

    Conservative: index unless the page shows no AI/platform signal at all and
    isn't a release/paper/research item or part of a storyline.
    """
    if str(rec.get("type") or "").lower() in ON_TOPIC_TYPES:
        return True
    if str(rec.get("sid") or "") in storyline_sids:
        return True
    if rec.get("matched_topics"):
        return True
    haystack = " ".join(
        str(rec.get(f) or "")
        for f in ("title", "summary", "summary_1line", "why_it_matters")
    ).lower()
    return any(term in haystack for term in AI_TERMS)


def related_stories(
    rec: dict, stories: dict[str, dict], storyline_of: dict[str, tuple] | None = None
) -> list[dict]:
    """Strongly related stories published at/before this story.

    Storyline members show only their own thread history. Other pages require a
    rare shared title anchor or continuity within one release feed. Same-source
    alone and ranked-topic overlap are deliberately insufficient: they produced
    unrelated arXiv papers and generic "agent" recommendations. Looking
    backward keeps rendered pages stable as new stories arrive.
    """
    storyline_of = storyline_of or {}
    my_slug = (storyline_of.get(str(rec.get("sid") or "")) or (None,))[0]
    topics = {squeeze(t).casefold() for t in rec.get("matched_topics") or [] if squeeze(t)}
    token_map = {
        str(item.get("sid") or ""): title_tokens(item.get("title"))
        for item in stories.values()
    }
    token_df = Counter(tok for tokens in token_map.values() for tok in tokens)
    # Related cards are a precision surface, so use a stricter rarity cap than
    # storyline discovery (1.5% vs 2% of the store). This keeps generic terms
    # such as "learning" from linking otherwise-unrelated papers.
    rare_cap = max(5, round(len(stories) * 0.015))

    def rare_title_tokens(item: dict) -> set[str]:
        return {
            tok
            for tok in token_map.get(str(item.get("sid") or ""), set())
            if tok not in STORYLINE_WEAK and token_df[tok] <= rare_cap
        }

    strong_title = rare_title_tokens(rec)
    cutoff = story_dt(rec)
    scored = []
    for other in stories.values():
        if other.get("sid") == rec.get("sid") or story_dt(other) > cutoff:
            continue
        other_topics = {
            squeeze(t).casefold() for t in other.get("matched_topics") or [] if squeeze(t)
        }
        shared_topics = topics & other_topics
        shared_title = strong_title & rare_title_tokens(other)
        same_source = other.get("source") == rec.get("source")
        release_series = (
            same_source
            and str(rec.get("type") or "").lower() == "release"
            and str(other.get("type") or "").lower() == "release"
        )
        other_slug = (storyline_of.get(str(other.get("sid") or "")) or (None,))[0]
        co_thread = bool(my_slug and other_slug == my_slug)
        qualifies = co_thread if my_slug else bool(shared_title or release_series)
        if qualifies:
            score = (
                100 * int(co_thread)
                + 20 * len(shared_title)
                + 2 * len(shared_topics)
                + 3 * int(release_series)
            )
            scored.append((score, story_dt(other), other))
    scored.sort(key=lambda t: (t[0], t[1]), reverse=True)
    return [other for _, _, other in scored[:RELATED_STORIES_MAX]]


def render_story_body(
    rec: dict, stories: dict[str, dict], storyline_of: dict[str, tuple] | None = None
) -> str:
    parts = []
    storyline_of = storyline_of or {}
    url = str(rec.get("url") or "")
    why = story_why(rec)
    if why:
        parts.append(
            '<div class="intro"><p class="tldr-label">Why it matters</p>'
            f"<p>{escape(why)}</p></div>"
        )

    # Up-link to the storyline this story belongs to. The richest context for a
    # member story lives one hop away in its timeline; surfacing it turns an
    # otherwise-thin permalink into an entry point to the memory layer.
    member = storyline_of.get(str(rec.get("sid") or ""))
    if member:
        slug, label = member
        parts.append(
            '<div class="intro"><p class="tldr-label">Part of a storyline</p>'
            f'<p><a class="primary" href="/storyline/{escape(slug)}">'
            f"{escape(label)} — see the full timeline →</a></p></div>"
        )

    img = str(rec.get("image_url") or "")
    img_html = (
        f'<img class="story-img" src="{escape(img)}" alt="" loading="lazy" '
        'onerror="this.remove()" />'
        if img.startswith(("http://", "https://"))
        else ""
    )
    highlights = [squeeze(h) for h in rec.get("release_highlights") or [] if squeeze(h)]
    # Release summaries are built from the same changelog bullets as the
    # highlights, so showing both would duplicate the page.
    summary = "" if highlights else story_brief(rec)
    if summary:
        parts.append(
            '<div class="story-lead"><div><p class="tldr-label">In brief</p>'
            f'<p class="story-summary">{escape(summary)}</p></div>{img_html}</div>'
        )
    elif img_html:
        parts.append(f'<div class="story-lead">{img_html}</div>')

    # Framing line for a story with no real body content and no storyline
    # context box above — guarantees the page explains itself and points out to
    # the source instead of rendering a bare title + buttons shell.
    if not (why or highlights or summary or member):
        when = fmt_story_date(story_dt(rec))
        when_bit = f", published {escape(when)}" if when else ""
        parts.append(
            f'<p class="story-framing">A brief from <strong>'
            f"{escape(source_label(rec, url))}</strong>{when_bit}. "
            "Open the original below for the full text.</p>"
        )

    if highlights:
        items = "".join(f"<li>{escape(h)}</li>" for h in highlights)
        parts.append(
            '<div class="tldr"><p class="tldr-label">Release highlights</p>'
            f"<ul>{items}</ul></div>"
        )

    topics = [squeeze(t) for t in rec.get("matched_topics") or [] if squeeze(t)]
    if topics:
        chips = "".join(f'<span class="badge">{escape(t)}</span>' for t in topics)
        parts.append(f'<div class="chips">{chips}</div>')

    feed_link = f"/?item={quote(url, safe='')}&utm_source=story"
    actions = [
        f'<a class="primary" href="{escape(url)}" target="_blank" rel="noopener" '
        f'data-track="story-source">Read the original at {escape(source_domain(url))} →</a>',
        f'<a href="{escape(feed_link)}">Open in live feed</a>',
    ]
    day = story_dt(rec).date().isoformat()
    if (DAILY_DIR / f"{day}.json").is_file():
        actions.append(f'<a href="/daily/{day}">Daily recap for {escape(day)}</a>')
    parts.append(f'<div class="story-actions">{"".join(actions)}</div>')

    covered = [c for c in rec.get("also_covered") or [] if isinstance(c, dict)]
    if covered:
        rows = []
        for c in covered:
            href = safe_http_url(c.get("url"))
            label = squeeze(c.get("title")) or squeeze(c.get("source")) or href
            src = squeeze(c.get("source"))
            suffix = f' <span class="muted">({escape(src)})</span>' if src else ""
            rows.append(
                f'<li><a href="{escape(href)}" target="_blank" rel="noopener">'
                f"{escape(label)}</a>{suffix}</li>"
            )
        parts.append(
            '<div class="covered"><p class="tldr-label">Also covered by</p>'
            f'<ul>{"".join(rows)}</ul></div>'
        )

    related = related_stories(rec, stories, storyline_of)
    if related:
        cards = []
        for other in related:
            meta = []
            if other.get("source"):
                meta.append(f'<span class="badge">{escape(str(other["source"]))}</span>')
            meta.append(f'<span class="badge">{escape(fmt_story_date(story_dt(other)))}</span>')
            cards.append(
                "<article>"
                f'<h3><a href="/story/{escape(str(other.get("sid")))}" data-track="story-related">'
                f'{escape(squeeze(other.get("title")) or "Untitled")}</a></h3>'
                f'<div class="art-meta">{"".join(meta)}</div></article>'
            )
        parts.append(
            '<section class="cat"><h2>Related stories '
            f'<span class="count">{len(cards)} item{"" if len(cards) == 1 else "s"}</span></h2>'
            f'<div class="articles">{"".join(cards)}</div></section>'
        )
    return "".join(parts)


def render_story_pages(
    base_url: str, stories: dict[str, dict], storyline_of: dict[str, tuple] | None = None
) -> tuple[list[tuple[str, str | None]], int]:
    """Render web/story/<sid>.html for every stored story.

    Every story still gets a page (so shared links keep resolving), but
    off-topic OR genuinely thin (no body content) stories are rendered with
    robots=noindex,follow and excluded from the returned sitemap list — we don't
    advertise a contentless shell to crawlers. ``storyline_of`` maps a member
    sid to its ``(slug, label)``; membership keeps a story on-topic and threads
    the up-link/related boost. Returns (sitemap_entries, noindexed_count) where
    sitemap_entries are (sid, lastmod) pairs newest first.
    """
    out_dir = WEB_DIR / "story"
    storyline_of = storyline_of or {}
    sitemap_entries: list[tuple[str, str | None]] = []
    written: set[str] = set()
    noindexed = 0
    ordered = sorted(stories.values(), key=story_dt, reverse=True)
    for rec in ordered:
        sid = str(rec.get("sid") or "")
        url = str(rec.get("url") or "")
        title = squeeze(rec.get("title"))
        if not SID_HTML_RE.match(f"{sid}.html") or not title or not url:
            continue
        canonical = f"{base_url}/story/{sid}"
        published_dt = parse_dt(rec.get("published"))
        published = published_dt.isoformat() if published_dt else None
        source = squeeze(rec.get("source"))
        kind = squeeze(rec.get("type"))
        member = storyline_of.get(sid)
        # A summary that just echoes the title is not real content (see
        # render_story_body) — exclude it from both the body-content signal and
        # the meta/OG description so neither shows the title twice.
        title_cf = title.casefold()
        why = story_why(rec)
        highlights = [h for h in rec.get("release_highlights") or [] if squeeze(h)]
        body_summary = story_brief(rec)
        has_content = bool(why or highlights or body_summary)
        # Description: first non-title-echo candidate, else a synthesized line so
        # the social/search snippet never just repeats the headline.
        desc_src = next(
            (
                c
                for c in (
                    story_brief(rec),
                    story_why(rec),
                )
                if c and c.casefold() != title_cf
            ),
            "",
        )
        if desc_src:
            description = clip(desc_src, 250)
        else:
            description = " · ".join(
                b for b in (source_label(rec, url), kind or "story", fmt_story_date(story_dt(rec))) if b
            ) + " — tracked on LLM Digest"
        meta_bits = [b for b in (source, fmt_story_date(story_dt(rec)), kind) if b]
        image = str(rec.get("image_url") or "")
        # Members are substantive (storyline up-link + co-thread related), so they
        # stay indexable; a non-member with no body is a thin shell -> noindex.
        indexable = is_on_topic(rec, storyline_of) and (has_content or bool(member))
        if member:
            crumbs = [
                ("Home", "/"),
                ("Storylines", "/storylines"),
                (member[1], f"/storyline/{member[0]}"),
                (title, f"/story/{sid}"),
            ]
        else:
            crumbs = [("LLM Digest", "/"), (title, f"/story/{sid}")]
        html = render_page(
            title=title,
            description=description,
            canonical=canonical,
            published=published,
            h1="📰 Story",
            meta_line=" · ".join(meta_bits),
            nav_links=[("/", "← Live feed"), ("/storylines", "📈 Storylines"), ("/daily", "📰 Daily recap"), ("/weekly", "🗓️ Weekly recap"), ("/rss.xml", "🔔 RSS")],
            json_href="",
            archive="",
            recap_title="",  # replaced by linked title below
            recap_range="",
            intro_html="",
            body_html=render_story_body(rec, stories, storyline_of),
            image=image,
            robots="" if indexable else "noindex,follow",
            json_ld=[
                article_node(
                    type_="NewsArticle",
                    title=title,
                    description=description,
                    canonical=canonical,
                    published=published,
                    base_url=base_url,
                    image=image,
                    source_url=url,
                ),
                breadcrumb_node(base_url, crumbs),
            ],
            title_html=(
                f'<h2 class="recap-title story-title"><a href="{escape(safe_http_url(url))}" '
                f'target="_blank" rel="noopener">{escape(title)}</a></h2>'
            ),
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{sid}.html").write_text(html, encoding="utf-8")
        written.add(f"{sid}.html")
        if indexable:
            sitemap_entries.append((sid, published_dt.date().isoformat() if published_dt else None))
        else:
            noindexed += 1
    prune_orphans(out_dir, SID_HTML_RE, written)
    return sitemap_entries, noindexed


def load_storyline_details() -> list[dict]:
    """Every per-slug storyline timeline file (never pruned; shared links live on).

    Excludes index.json and the agent/scout sidecar subdirectories.
    """
    details = []
    if not STORYLINES_DIR.is_dir():
        return details
    for path in sorted(STORYLINES_DIR.glob("*.json")):
        if path.name == "index.json" or not SLUG_RE.match(path.stem):
            continue
        data = load_json(path)
        if isinstance(data, dict) and data.get("slug") and data.get("days"):
            details.append(data)
    return details


def storyline_membership(details: list[dict]) -> dict[str, tuple]:
    """Map each member story sid -> ``(slug, label)`` of the storyline it's in.

    Keys double as the member-sid set (keeps members indexable in is_on_topic).
    First storyline wins if a story somehow appears in more than one.
    """
    out: dict[str, tuple] = {}
    for sl in details:
        slug = str(sl.get("slug") or "")
        if not slug:
            continue
        label = squeeze(sl.get("label")) or slug
        for day in sl.get("days") or []:
            for it in day.get("items") or []:
                sid = str(it.get("sid") or "")
                if sid and sid not in out:
                    out[sid] = (slug, label)
    return out


# Semantic tones for the storyline arc. Drive node/kicker colors and the rail.
# Mirrored in .agents/skills/storyline-editor (storyline_common.STORYLINE_TONES).
STORYLINE_TONES = ("launch", "rising", "turn", "now", "resolved", "alert", "neutral")


def _sl_short_date(value) -> str:
    """'Jun 10' style label from an ISO timestamp/date (empty on failure)."""
    pub = iso_or_none(value)
    if not pub:
        return ""
    d = datetime.fromisoformat(pub)
    return f"{d.strftime('%b')} {d.day}"


def _sl_date_range(items: list[dict]) -> str:
    """'Jun 10' / 'Jun 10–13' / 'Jun 30 – Jul 2' from a beat's items, ordered by
    real publish time (so day numbers and month rollovers sort correctly)."""
    dated = []
    for it in items:
        pub = iso_or_none(it.get("published"))
        if pub:
            dated.append(datetime.fromisoformat(pub))
    if not dated:
        return ""
    lo, hi = min(dated), max(dated)
    lo_lbl = f"{lo.strftime('%b')} {lo.day}"
    if lo.date() == hi.date():
        return lo_lbl
    if lo.month == hi.month:
        return f"{lo_lbl}–{hi.day}"
    return f"{lo_lbl} – {hi.strftime('%b')} {hi.day}"


def _sl_item_card(
    it: dict, story_sids: set[str], emphasize: bool = False
) -> str:
    """One source card revealed when a beat is expanded. Kept deliberately plain
    (title + source/date + note) — agent provenance lives in the beat meta line,
    not as per-card pills, so the spine stays clean. ``emphasize`` tints the
    pivotal turn beat's cards."""
    href = safe_http_url(it.get("url"))
    sid = story_sid(it.get("url")) if href != "#" else ""
    # Prefer the internal story permalink (hub -> spoke) when we have one.
    title_href = f"/story/{sid}" if sid and sid in story_sids else href
    attrs = "" if title_href.startswith("/") else ' target="_blank" rel="noopener"'
    meta = []
    if it.get("source"):
        meta.append(f'<span class="badge">{escape(str(it.get("source")))}</span>')
    short = _sl_short_date(it.get("published"))
    if short:
        meta.append(f'<span class="badge">{escape(short)}</span>')
    if it.get("sources") and len(it["sources"]) > 1:
        meta.append(f'<span class="badge">{len(it["sources"])} sources</span>')
    note = squeeze(it.get("editor_note")) or squeeze(it.get("summary_1line"))
    note_html = f'<p class="art-summary">{escape(note)}</p>' if note else ""
    cls = "sl-card sl-card-turn" if emphasize else "sl-card"
    return (
        f'<article class="{cls}">'
        f'<h3><a href="{escape(title_href)}"{attrs} data-track="storyline-link">'
        f'{escape(squeeze(it.get("title")) or "Untitled")}</a></h3>'
        f'<div class="art-meta">{"".join(meta)}</div>{note_html}</article>'
    )


def _sl_timeline_view(sl: dict, story_sids: set[str]) -> str:
    """Classic day-by-day timeline (the fallback view, and the un-narrated one)."""
    parts = []
    for i, day in enumerate(sl.get("days") or []):
        items = day.get("items") or []
        if not items:
            continue
        cards = "".join(_sl_item_card(it, story_sids) for it in items)
        parts.append(
            f'<section class="cat"><h2><span class="count">Day {i + 1}</span> '
            f'{escape(fmt_long_date(str(day.get("date") or "")))}</h2>'
            f'<div class="articles">{cards}</div></section>'
        )
    return "".join(parts)


def _sl_access_track(status: dict) -> str:
    """The 'Access over time' bar — proportional, tone-colored phases with
    labeled ends. Driven by the optional ``status.track`` segment list."""
    track = (status or {}).get("track") if isinstance(status, dict) else None
    if not isinstance(track, list) or not track:
        return ""
    segs, weights = [], []
    for s in track:
        w = max(float(s.get("weight") or 1), 0.0001)
        weights.append(w)
    total = sum(weights) or 1
    for s, w in zip(track, weights):
        tone = _sl_tone(s)
        segs.append(
            f'<span class="sl-track-seg tone-{tone}-bg" style="flex:0 0 {w / total * 100:.3f}%"></span>'
        )

    def _end(seg: dict, dot_left: bool) -> str:
        tone = _sl_tone(seg)
        label = squeeze(seg.get("label"))
        detail = squeeze(seg.get("detail"))
        text = label + (f" · {detail}" if detail else "")
        dot = "● " if dot_left else ""
        tail = "" if dot_left else " ●"
        return f'<span class="tone-{tone}-fg">{dot}{escape(text)}{tail}</span>'

    ends = f"{_end(track[0], True)}{_end(track[-1], False)}"
    return (
        '<p class="sl-rail-label">Access over time</p>'
        f'<div class="sl-track">{"".join(segs)}</div>'
        f'<div class="sl-track-ends">{ends}</div>'
    )


def _sl_beat_sources(items: list[dict]) -> int:
    """Distinct source count across a beat's items (for 'verified across N')."""
    srcs: set[str] = set()
    for it in items:
        if it.get("source"):
            srcs.add(str(it["source"]))
        for s in it.get("sources") or []:
            srcs.add(str(s))
    return len(srcs)


def _sl_arc_view(
    sl: dict, beats: list[dict], story_sids: set[str], prov: dict, status: dict
) -> str:
    """The narrative arc: an access track + a spine of editor-defined beats, each
    grouping the source items that moved the story. Items not placed in any beat
    are swept into a trailing 'More in this thread' beat so nothing is dropped."""
    by_sid: dict[str, dict] = {}
    for day in sl.get("days") or []:
        for it in day.get("items") or []:
            if it.get("sid"):
                by_sid[str(it["sid"])] = it

    placed: set[str] = set()
    rendered: list[tuple[dict, list[dict]]] = []  # (beat, items)
    for beat in beats:
        items = [by_sid[s] for s in beat.get("sids") or [] if s in by_sid]
        if not items:
            continue
        placed.update(str(it["sid"]) for it in items)
        rendered.append((beat, items))
    leftover = [it for sid, it in by_sid.items() if sid not in placed]
    if leftover:
        rendered.append(
            ({"kicker": "More", "tone": "neutral", "headline": "More in this thread"}, leftover)
        )
    if not rendered:
        return ""

    # Prefer the editor's access track; fall back to a one-segment-per-beat rail.
    track = _sl_access_track(status)
    if not track:
        segs = "".join(
            f'<span class="sl-rail-seg tone-{_sl_tone(b)}-bg"></span>' for b, _ in rendered
        )
        first_lbl = _sl_short_date((rendered[0][1] or [{}])[0].get("published"))
        last_lbl = _sl_short_date((rendered[-1][1] or [{}])[-1].get("published"))
        track = (
            '<p class="sl-rail-label">Arc</p>'
            f'<div class="sl-rail">{segs}</div>'
            f'<div class="sl-rail-ends"><span>{escape(first_lbl)}</span>'
            f"<span>{escape(last_lbl)} · now</span></div>"
        )

    blocks = []
    for idx, (beat, items) in enumerate(rendered):
        tone = _sl_tone(beat)
        when = _sl_date_range(items)
        kicker = squeeze(beat.get("kicker")) or "UPDATE"
        kicker_txt = f"{kicker.upper()}" + (f" · {when}" if when else "")
        summary = squeeze(beat.get("summary"))
        # If any item in the beat is editor-verified, surface a corroboration
        # line. The count is the editor's asserted source count (so it agrees
        # with the per-item badge), falling back to the beat's distinct sources.
        vcounts = []
        for it in items:
            v = (prov.get(str(it.get("sid"))) or {}).get("verified")
            if isinstance(v, (int, float)) and not isinstance(v, bool):
                vcounts.append(int(v))
            elif v:
                vcounts.append(0)
        verified = bool(vcounts)
        n_sources = max(vcounts) if vcounts and max(vcounts) > 1 else _sl_beat_sources(items)
        check = (
            f' <span class="sl-ok">✓ fact-checker verified across {n_sources} sources</span>'
            if verified
            else ""
        )
        # Only the turn beat shows a descriptive line by default (it carries the
        # corroboration note); the rest stay a clean headline + meta line.
        sum_html = (
            f'<div class="sl-beat-sum">{escape(summary)}{check}</div>'
            if ((summary and tone == "turn") or check)
            else ""
        )
        n = len(items)
        # Agent attribution as quiet text in the meta line (not pills): which
        # agent surfaced or re-statused this beat, from the provenance map.
        hints = []
        if any(
            str((prov.get(str(it.get("sid"))) or {}).get("surfaced_by") or "").lower() == "scout"
            for it in items
        ):
            hints.append("scout")
        if any((prov.get(str(it.get("sid"))) or {}).get("status_update") for it in items):
            hints.append("watcher updated status")
        meta = f'{n} source{"s" if n != 1 else ""}'
        if hints:
            meta += " · " + " · ".join(hints)
        show = f"show source{'s' if n != 1 else ''} ▾"
        cards = "".join(
            _sl_item_card(it, story_sids, emphasize=(tone == "turn")) for it in items
        )
        # Beats are collapsed by default — the spine reads as a scannable arc;
        # click any beat to reveal its source cards.
        blocks.append(
            f'<details class="sl-beat tone-{tone}">'
            '<summary><span class="sl-node"></span>'
            f'<div class="sl-kicker">{escape(kicker_txt)}</div>'
            f'<div class="sl-beat-title">{escape(squeeze(beat.get("headline")) or "Update")}</div>'
            f'{sum_html}'
            f'<div class="sl-show">{escape(meta)} · <span class="sl-show-link">{escape(show)}</span></div>'
            f'</summary><div class="sl-cards">{cards}</div></details>'
        )
    return f'{track}<div class="sl-spine">{"".join(blocks)}</div>'


def _sl_tone(obj: dict) -> str:
    tone = str((obj or {}).get("tone") or "neutral").lower()
    return tone if tone in STORYLINE_TONES else "neutral"


def _sl_status_banner(status: dict) -> str:
    if not isinstance(status, dict):
        return ""
    state = squeeze(status.get("state"))
    detail = squeeze(status.get("detail"))
    if not state and not detail:
        return ""
    tone = _sl_tone(status)
    meta_bits = []
    changed = _sl_short_date(status.get("changed")) or squeeze(status.get("changed"))
    if changed:
        meta_bits.append(f"status changed {changed}")
    if squeeze(status.get("reenable")):
        meta_bits.append(squeeze(status.get("reenable")))
    meta = (
        f'<span class="sl-status-meta">{escape(" · ".join(meta_bits))}</span>'
        if meta_bits
        else ""
    )
    state_html = f'<span class="sl-state">{escape(state)}</span>' if state else ""
    detail_html = f'<p class="sl-status-detail">{escape(detail)}</p>' if detail else ""
    return (
        f'<div class="sl-status tone-{tone}">'
        f'<div class="sl-status-head"><span class="sl-dot"></span>{state_html}{meta}</div>'
        f"{detail_html}</div>"
    )


def _sl_watch(open_questions: list, take: str) -> str:
    qs = [squeeze(q) for q in (open_questions or []) if squeeze(q)]
    take = squeeze(take)
    if not qs and not take:
        return ""
    inner = '<p class="sl-watch-label">What to watch — open questions</p>'
    if qs:
        lis = "".join(f"<li>{escape(q)}</li>" for q in qs)
        inner += f"<ul>{lis}</ul>"
    if take:
        inner += (
            f'<div class="sl-take">💡 <b>Take for builders:</b> {escape(take)}</div>'
        )
    return f'<div class="sl-watch">{inner}</div>'


def _sl_agents(sl: dict, beats: list[dict], prov: dict, status: dict) -> list[tuple[str, str, str]]:
    """The named agents that touched this thread, as (css, name, what) — each
    backed by a real signal so the strip never claims work that didn't happen:
    scout from ``via_scout``/provenance, editor from the narrative, fact-checker
    from editor-verified items, watcher from status changes."""
    rows: list[tuple[str, str, str]] = []
    scout_n = sum(1 for p in prov.values() if str((p or {}).get("surfaced_by") or "").lower() == "scout")
    if sl.get("via_scout") or scout_n:
        what = f"surfaced {scout_n}" if scout_n else "surfaced this thread"
        rows.append(("a-scout", "scout", what))
    ed = sl.get("editorial") or {}
    if ed.get("tldr"):
        nb = len([b for b in beats if b.get("sids")])
        rows.append(("a-editor", "editor", f"wrote the arc · {nb} beats" if nb else "wrote TL;DR"))
    verified_n = sum(1 for p in prov.values() if (p or {}).get("verified"))
    if verified_n:
        rows.append(("a-check", "fact-checker", f"{verified_n} verified"))
    status_n = sum(1 for p in prov.values() if (p or {}).get("status_update"))
    if not status_n and isinstance(status, dict) and status.get("changed"):
        status_n = 1
    if status_n:
        rows.append(("a-watch", "watcher", f"{status_n} status change" + ("s" if status_n != 1 else "")))
    return rows


def _sl_agents_strip(agents: list[tuple[str, str, str]]) -> str:
    if not agents:
        return ""
    bits = [
        f'<span><b class="{css}">{escape(name)}</b> {escape(what)}</span>'
        for css, name, what in agents
    ]
    return (
        '<div class="sl-agents"><p class="sl-watch-label">Agents on this story</p>'
        f'<div class="sl-agent-row">{"".join(bits)}</div></div>'
    )


SL_FOOTER_NOTE = (
    "Storylines are threaded mechanically from the feed: stories that share a "
    "distinctive anchor across multiple days and sources. Each item links to "
    "its original source. The arc, status, and open questions are written by "
    "the editor routine and refreshed whenever a new beat lands."
)


def storyline_hero(sl: dict) -> str:
    """The bespoke storyline header: the story name as the hero H1 with an inline
    Follow button (passed to render_page as ``title_html``), so the page reads as
    a dedicated story rather than a generic recap with the name demoted."""
    label = squeeze(sl.get("label")) or str(sl.get("slug") or "")
    slug = str(sl.get("slug") or "")
    last_updated = str(sl.get("last_updated") or "")
    return (
        '<div class="sl-hero">'
        f'<h2 class="recap-title">{escape(label)}</h2>'
        '<button id="followBtn" type="button" class="primary" '
        f'data-slug="{escape(slug)}" data-last-updated="{escape(last_updated)}" '
        'aria-pressed="false">+ Follow this story</button>'
        "</div>"
    )


def render_storyline_body(sl: dict, story_sids: set[str]) -> str:
    parts = []
    ed = sl.get("editorial") or {}
    parts.append(_sl_status_banner(ed.get("status")))

    tldr = squeeze(ed.get("tldr"))
    whats_new = squeeze(ed.get("whats_new"))
    if tldr or whats_new:
        bits = []
        if tldr:
            bits.append('<p class="tldr-label">TL;DR</p>' f"<p>{escape(tldr)}</p>")
        if whats_new:
            bits.append(f"<p><b>What's new:</b> {escape(whats_new)}</p>")
        parts.append(f'<div class="intro">{"".join(bits)}</div>')

    status = ed.get("status") if isinstance(ed.get("status"), dict) else {}
    prov = ed.get("provenance") if isinstance(ed.get("provenance"), dict) else {}
    beats = [b for b in (ed.get("beats") or []) if isinstance(b, dict)]
    agents = _sl_agents(sl, beats, prov, status)
    arc_html = _sl_arc_view(sl, beats, story_sids, prov, status) if beats else ""
    timeline_html = _sl_timeline_view(sl, story_sids)

    if arc_html:
        note = f"maintained by {len(agents)} agents" if agents else "narrated by the editor"
        parts.append(
            '<div class="sl-tabs">'
            '<button class="sl-tab is-active" type="button" data-view="arc">The Arc</button>'
            '<button class="sl-tab" type="button" data-view="timeline">Timeline</button>'
            f'<span class="sl-tab-note">{escape(note)}</span></div>'
        )
        parts.append(f'<div data-sl-view="arc">{arc_html}</div>')
        parts.append(f'<div data-sl-view="timeline" hidden>{timeline_html}</div>')
    else:
        parts.append(timeline_html)

    take = squeeze(ed.get("take_for_builders")) or squeeze(ed.get("why_it_matters"))
    parts.append(_sl_watch(ed.get("open_questions"), take))
    parts.append(_sl_agents_strip(agents))
    parts.append(f'<p class="sl-note">{escape(SL_FOOTER_NOTE)}</p>')
    return "".join(p for p in parts if p)


def render_storyline_pages(
    base_url: str, details: list[dict], active_slugs: set[str], story_sids: set[str]
) -> list[tuple[str, str | None]]:
    """Render web/storyline/<slug>.html for every storyline timeline file.

    Active storylines (still in the index window) are returned for the sitemap;
    aged-out threads stay rendered so shared links keep working, just unlisted.
    """
    out_dir = WEB_DIR / "storyline"
    sitemap_entries: list[tuple[str, str | None]] = []
    written: set[str] = set()
    for sl in details:
        slug = str(sl.get("slug") or "")
        if not SLUG_RE.match(slug):
            continue
        label = squeeze(sl.get("label")) or slug
        title = f"{label} — AI storyline"
        ed = sl.get("editorial") or {}
        description = clip(
            squeeze(ed.get("tldr")) or squeeze(sl.get("latest_title")) or label, 250
        )
        canonical = f"{base_url}/storyline/{slug}"
        first_seen = iso_or_none(sl.get("first_seen"))
        last_updated = iso_or_none(sl.get("last_updated"))
        meta_bits = [
            f"{sl.get('item_count', 0)} items",
            f"{sl.get('source_count', 0)} sources",
            f"{sl.get('day_count', 0)} days",
        ]
        html = render_page(
            title=title,
            description=description,
            canonical=canonical,
            published=first_seen,
            h1="📈 AI Storyline",
            meta_line=" · ".join(meta_bits),
            nav_links=[("/storylines", "← All storylines"), ("/", "📰 Live feed"), ("/daily", "🗓️ Daily recap"), ("/rss.xml", "🔔 RSS")],
            json_href=f"/api/storylines?slug={slug}",
            archive="",
            recap_title=label,
            recap_range="",
            title_html=storyline_hero(sl),
            intro_html="",
            body_html=render_storyline_body(sl, story_sids),
            json_ld=[
                article_node(
                    type_="NewsArticle",
                    title=title,
                    description=description,
                    canonical=canonical,
                    published=first_seen,
                    base_url=base_url,
                ),
                breadcrumb_node(
                    base_url,
                    [("Home", "/"), ("Storylines", "/storylines"), (label, f"/storyline/{slug}")],
                ),
            ],
            extra_js=STORYLINE_FOLLOW_JS + STORYLINE_ARC_JS,
            extra_css=STORYLINE_ARC_CSS,
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{slug}.html").write_text(html, encoding="utf-8")
        written.add(f"{slug}.html")
        if slug in active_slugs:
            lastmod = (last_updated or first_seen or "")[:10] or None
            sitemap_entries.append((slug, lastmod))
    prune_orphans(out_dir, SLUG_HTML_RE, written)
    sitemap_entries.sort(key=lambda t: t[1] or "", reverse=True)
    return sitemap_entries


def load_wiki() -> dict:
    """The compiled agent-engineering wiki (pipeline/build_wiki.py output)."""
    return load_json(WIKI_DIR / "index.json") or {}


KIND_BADGE = {"obstacle": "🧱 Obstacle", "solution": "🛠️ Solution"}


def render_topic_body(node: dict, nodes: dict) -> str:
    """Body for a single /topic/<slug> node: sections + cross-links + evidence."""
    parts: list[str] = []
    for sec in node.get("sections") or []:
        heading = squeeze(sec.get("heading"))
        html = sec.get("html") or ""
        if not html:
            continue
        parts.append(f'<div class="cat"><h2>{escape(heading)}</h2>{html}</div>')

    # Cross-links: obstacle -> solutions, solution -> obstacles.
    if node["kind"] == "obstacle":
        linked, link_label = node.get("solutions") or [], "Solutions"
    else:
        linked, link_label = node.get("obstacles") or [], "Addresses"
    if linked:
        chips = "".join(
            f'<a href="/topic/{escape(l["slug"])}">{escape(squeeze(l["title"]))}</a>'
            for l in linked
            if l.get("slug") in nodes
        )
        parts.append(f'<div class="cat"><h2>{link_label}</h2><div class="toc">{chips}</div></div>')

    storylines = node.get("related_storylines") or []
    evidence = node.get("evidence") or []
    if storylines or evidence:
        items = []
        for sl in storylines:
            items.append(
                f'<li><a href="/storyline/{escape(sl["slug"])}">📈 {escape(squeeze(sl["label"]))}</a> '
                "<span class=\"muted\">— storyline</span></li>"
            )
        for ev in evidence:
            items.append(
                f'<li><a href="/story/{escape(ev["sid"])}">{escape(squeeze(ev["title"]))}</a></li>'
            )
        parts.append(
            '<div class="cat covered"><h2>Evidence</h2><ul>' + "".join(items) + "</ul></div>"
        )
    return "\n".join(parts)


def render_topic_pages(base_url: str, wiki: dict) -> list[tuple[str, str | None]]:
    """Render web/topic/<slug>.html for every wiki node; return sitemap entries."""
    nodes = wiki.get("nodes") or {}
    out_dir = WEB_DIR / "topic"
    sitemap_entries: list[tuple[str, str | None]] = []
    written: set[str] = set()
    for slug, node in nodes.items():
        if not SLUG_RE.match(slug):
            continue
        title = squeeze(node.get("title")) or slug
        description = clip(squeeze(node.get("summary")) or title, 250)
        canonical = f"{base_url}/topic/{slug}"
        updated = iso_or_none(node.get("updated")) or node.get("updated") or None
        area_label = node.get("area") or ""
        meta_bits = [KIND_BADGE.get(node["kind"], node["kind"])]
        if area_label:
            meta_bits.append(str(area_label))
        if node.get("evidence"):
            meta_bits.append(f"{len(node['evidence'])} sources")
        html = render_page(
            title=f"{title} — agent engineering",
            description=description,
            canonical=canonical,
            published=None,
            h1="🧠 Agent Engineering Wiki",
            meta_line=" · ".join(meta_bits),
            nav_links=[("/map", "← Knowledge map"), ("/", "📰 Live feed"), ("/storylines", "📈 Storylines"), ("/rss.xml", "🔔 RSS")],
            json_href="",
            archive="",
            recap_title=title,
            recap_range="",
            intro_html="",
            body_html=render_topic_body(node, nodes),
            json_ld=[
                article_node(
                    type_="Article",
                    title=title,
                    description=description,
                    canonical=canonical,
                    published=None,
                    base_url=base_url,
                ),
                breadcrumb_node(
                    base_url,
                    [("Home", "/"), ("Knowledge map", "/map"), (title, f"/topic/{slug}")],
                ),
            ],
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{slug}.html").write_text(html, encoding="utf-8")
        written.add(f"{slug}.html")
        lastmod = (updated or "")[:10] or None
        sitemap_entries.append((slug, lastmod))
    prune_orphans(out_dir, SLUG_HTML_RE, written)
    sitemap_entries.sort(key=lambda t: t[0])
    return sitemap_entries


def render_map_page(base_url: str, wiki: dict) -> bool:
    """Render web/map.html — the obstacle→solution index. False if no nodes."""
    nodes = wiki.get("nodes") or {}
    areas = wiki.get("areas") or []
    if not nodes:
        return False
    blocks: list[str] = []
    for area in areas:
        cards = []
        for slug in area.get("obstacles") or []:
            node = nodes.get(slug)
            if not node:
                continue
            sols = "".join(
                f'<a href="/topic/{escape(s["slug"])}">{escape(squeeze(s["title"]))}</a>'
                for s in node.get("solutions") or []
            )
            sol_html = f'<div class="toc">{sols}</div>' if sols else ""
            cards.append(
                "<article>"
                f'<h3 class="story-title"><a href="/topic/{escape(slug)}">{escape(squeeze(node.get("title")) or slug)}</a></h3>'
                f'<p class="art-summary">{escape(clip(squeeze(node.get("summary")), 200))}</p>'
                f"{sol_html}</article>"
            )
        if cards:
            blocks.append(
                f'<div class="cat"><h2>{escape(squeeze(area.get("label")) or area.get("area"))} '
                f'<span class="count">{len(cards)}</span></h2>'
                f'<div class="articles">{"".join(cards)}</div></div>'
            )
    body = "\n".join(blocks) or "<p>No topics yet.</p>"
    canonical = f"{base_url}/map"
    description = (
        "A living map of the obstacles to building and operating AI agents — "
        "memory, reliability, tool use, cost, and more — each linked to the "
        "solutions the field uses, with source articles."
    )
    html = render_page(
        title="Agent Engineering Wiki — obstacles & solutions",
        description=description,
        canonical=canonical,
        published=None,
        h1="🧠 Agent Engineering Wiki",
        meta_line="Obstacles to building & operating agents, mapped to solutions",
        nav_links=[("/", "📰 Live feed"), ("/storylines", "📈 Storylines"), ("/daily", "🗓️ Daily"), ("/rss.xml", "🔔 RSS")],
        json_href="/api/topics",
        archive="",
        recap_title="Agent engineering: obstacles & solutions",
        recap_range="",
        intro_html=f'<div class="intro"><p>{escape(description)}</p></div>',
        body_html=body,
        json_ld=[
            breadcrumb_node(base_url, [("Home", "/"), ("Knowledge map", "/map")]),
        ],
    )
    (WEB_DIR / "map.html").write_text(html, encoding="utf-8")
    return True


def prune_orphans(out_dir: Path, html_re: re.Pattern, keep: set[str]) -> None:
    if not out_dir.is_dir():
        return
    for path in out_dir.glob("*.html"):
        if html_re.match(path.name) and path.name not in keep:
            path.unlink()
            print(f"pruned stale page: {path.relative_to(ROOT)}")


def week_end_date(week_id: str) -> str | None:
    """End (Sunday) of an ISO week id 'YYYY-Www', for sitemap lastmod."""
    m = re.match(r"^(\d{4})-W(\d{2})$", str(week_id))
    if not m:
        return None
    try:
        return date.fromisocalendar(int(m.group(1)), int(m.group(2)), 7).isoformat()
    except ValueError:
        return None


def write_sitemap(
    base_url: str,
    days: list[str],
    weeks: list[str],
    stories: list[tuple[str, str | None]] | None = None,
    storylines: list[tuple[str, str | None]] | None = None,
    topics: list[tuple[str, str | None]] | None = None,
) -> None:
    today = datetime.now(timezone.utc).date().isoformat()
    entries: list[tuple[str, str | None, str | None]] = [
        (f"{base_url}/", today, "hourly"),
        (f"{base_url}/daily", today, "daily"),
        (f"{base_url}/weekly", today, "weekly"),
        (f"{base_url}/storylines", today, "daily"),
        (f"{base_url}/voices", today, "monthly"),
    ]
    if topics:
        entries.append((f"{base_url}/map", today, "weekly"))
        entries += [
            (f"{base_url}/topic/{slug}", lastmod, "weekly") for slug, lastmod in topics
        ]
    entries += [(f"{base_url}/daily/{d}", d, None) for d in days]
    # Weekly recaps: lastmod = the week's end date (Sunday) when derivable.
    for w in weeks:
        entries.append((f"{base_url}/weekly/{w}", week_end_date(w), None))
    entries += [
        (f"{base_url}/storyline/{slug}", lastmod, "daily")
        for slug, lastmod in storylines or []
    ]
    entries += [(f"{base_url}/story/{sid}", lastmod, None) for sid, lastmod in stories or []]

    rows = []
    for loc, lastmod, changefreq in entries:
        parts = [f"<loc>{escape(loc)}</loc>"]
        if lastmod:
            parts.append(f"<lastmod>{escape(lastmod)}</lastmod>")
        if changefreq:
            parts.append(f"<changefreq>{escape(changefreq)}</changefreq>")
        rows.append("  <url>" + "".join(parts) + "</url>")
    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(rows)
        + "\n</urlset>\n"
    )
    (WEB_DIR / "sitemap.xml").write_text(xml, encoding="utf-8")


def write_robots(base_url: str) -> None:
    (WEB_DIR / "robots.txt").write_text(
        f"User-agent: *\nAllow: /\n\nSitemap: {base_url}/sitemap.xml\n", encoding="utf-8"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base-url", default=DEFAULT_BASE_URL, help="public site origin for canonical/sitemap URLs")
    args = ap.parse_args()
    base_url = args.base_url.rstrip("/")

    stories = load_store()
    story_sids = set(stories)

    storyline_details = load_storyline_details()
    index = load_json(STORYLINES_DIR / "index.json") or {}
    active_slugs = {
        str(s.get("slug"))
        for s in (index.get("storylines") or [])
        if isinstance(s, dict) and s.get("slug")
    }
    storyline_of = storyline_membership(storyline_details)

    days = render_daily_pages(base_url, story_sids)
    weeks = render_weekly_pages(base_url, story_sids)
    story_pages, noindexed = render_story_pages(base_url, stories, storyline_of)
    storyline_pages = render_storyline_pages(
        base_url, storyline_details, active_slugs, story_sids
    )
    wiki = load_wiki()
    topic_pages = render_topic_pages(base_url, wiki)
    has_map = render_map_page(base_url, wiki)
    write_sitemap(base_url, days, weeks, story_pages, storyline_pages, topic_pages)
    write_robots(base_url)
    print(
        f"static pages rendered: {len(days)} daily, {len(weeks)} weekly, "
        f"{len(story_pages) + noindexed} story ({noindexed} noindex), "
        f"{len(storyline_details)} storyline ({len(storyline_pages)} active), "
        f"{len(topic_pages)} topic ({'map' if has_map else 'no map'}) "
        "-> web/daily/, web/weekly/, web/story/, web/storyline/, web/topic/"
    )
    n_urls = 5 + len(days) + len(weeks) + len(story_pages) + len(storyline_pages)
    n_urls += (1 + len(topic_pages)) if topic_pages else 0
    print(f"sitemap: web/sitemap.xml ({n_urls} urls), robots: web/robots.txt")
    if not days and not weeks and not story_pages and not storyline_pages:
        print("warning: no recaps or stories found; nothing rendered", file=sys.stderr)


if __name__ == "__main__":
    main()
